import type { Exercise, ExerciseCategory } from "./types";

const e = (
  id: string,
  name: string,
  category: ExerciseCategory,
  muscles: Exercise["muscles"],
  equipment: string,
  pattern: Exercise["pattern"],
  metric: Exercise["metric"] = "weight_reps",
): Exercise => ({ id, name, category, muscles, equipment, pattern, metric });

/**
 * Extended exercise library — merged into EXERCISES in ./exercises.
 * Covers general strength, hypertrophy isolation, olympic lifting,
 * strongman, sport-specific skill work, conditioning and recovery.
 */
export const EXTRA_EXERCISES: Exercise[] = [
  // ---------- Barbell / general strength ----------
  e("bb-box-squat", "Barbell Box Squat", "resistance", ["quads", "glutes"], "Barbell", "legs"),
  e("bb-pause-squat", "Pause Back Squat", "resistance", ["quads", "glutes"], "Barbell", "legs"),
  e("bb-safety-bar-squat", "Safety Bar Squat", "resistance", ["quads", "back"], "Barbell", "legs"),
  e("bb-zercher-squat", "Zercher Squat", "resistance", ["quads", "core"], "Barbell", "legs"),
  e("bb-overhead-squat", "Overhead Squat", "resistance", ["quads", "shoulders"], "Barbell", "legs"),
  e("bb-split-squat", "Barbell Split Squat", "resistance", ["quads", "glutes"], "Barbell", "legs"),
  e("bb-good-morning", "Good Morning", "resistance", ["hamstrings", "back"], "Barbell", "pull"),
  e("bb-sumo-deadlift", "Sumo Deadlift", "resistance", ["glutes", "hamstrings"], "Barbell", "pull"),
  e("bb-deficit-deadlift", "Deficit Deadlift", "resistance", ["hamstrings", "back"], "Barbell", "pull"),
  e("bb-rack-pull", "Rack Pull", "resistance", ["back", "glutes"], "Barbell", "pull"),
  e("bb-snatch-grip-dl", "Snatch-Grip Deadlift", "resistance", ["back", "hamstrings"], "Barbell", "pull"),
  e("bb-trapbar-dl", "Trap Bar Deadlift", "resistance", ["quads", "glutes"], "Trap Bar", "pull"),
  e("bb-trapbar-jump", "Trap Bar Jump", "resistance", ["quads", "glutes"], "Trap Bar", "legs", "reps"),
  e("bb-close-grip-bench", "Close-Grip Bench Press", "resistance", ["triceps", "chest"], "Barbell", "push"),
  e("bb-floor-press", "Barbell Floor Press", "resistance", ["chest", "triceps"], "Barbell", "push"),
  e("bb-decline-bench", "Decline Barbell Press", "resistance", ["chest"], "Barbell", "push"),
  e("bb-spoto-press", "Spoto Press", "resistance", ["chest", "triceps"], "Barbell", "push"),
  e("bb-pin-press", "Pin Press", "resistance", ["chest", "shoulders"], "Barbell", "push"),
  e("bb-seated-ohp", "Seated Barbell Overhead Press", "resistance", ["shoulders", "triceps"], "Barbell", "push"),
  e("bb-behind-neck-press", "Behind-the-Neck Press", "resistance", ["shoulders"], "Barbell", "push"),
  e("bb-pendlay-row", "Pendlay Row", "resistance", ["back", "biceps"], "Barbell", "pull"),
  e("bb-yates-row", "Yates Row", "resistance", ["back", "biceps"], "Barbell", "pull"),
  e("bb-meadows-row", "Meadows Row", "resistance", ["back"], "Barbell", "pull"),
  e("bb-tbar-row", "T-Bar Row", "resistance", ["back", "biceps"], "Barbell", "pull"),
  e("bb-shrug", "Barbell Shrug", "resistance", ["back", "shoulders"], "Barbell", "pull"),
  e("bb-upright-row", "Upright Row", "resistance", ["shoulders", "back"], "Barbell", "pull"),
  e("bb-curl", "Barbell Biceps Curl", "resistance", ["biceps"], "Barbell", "pull"),
  e("bb-ez-curl", "EZ-Bar Curl", "resistance", ["biceps"], "Barbell", "pull"),
  e("bb-skullcrusher", "Skullcrusher", "resistance", ["triceps"], "Barbell", "push"),
  e("bb-jm-press", "JM Press", "resistance", ["triceps"], "Barbell", "push"),
  e("bb-landmine-press", "Landmine Press", "resistance", ["shoulders", "chest"], "Landmine", "push"),
  e("bb-landmine-rotation", "Landmine Rotation", "resistance", ["core"], "Landmine", "core"),
  e("bb-landmine-row", "Landmine Row", "resistance", ["back"], "Landmine", "pull"),
  e("bb-hip-thrust-single", "Single-Leg Hip Thrust", "resistance", ["glutes"], "Barbell", "legs"),
  e("bb-calf-raise", "Barbell Calf Raise", "resistance", ["calves"], "Barbell", "legs"),
  e("bb-wrist-curl", "Barbell Wrist Curl", "resistance", ["biceps"], "Barbell", "pull"),

  // ---------- Olympic lifting ----------
  e("oly-snatch", "Full Snatch", "resistance", ["full body", "shoulders"], "Barbell", "pull"),
  e("oly-power-snatch", "Power Snatch", "resistance", ["full body", "shoulders"], "Barbell", "pull"),
  e("oly-clean-jerk", "Clean & Jerk", "resistance", ["full body", "shoulders"], "Barbell", "push"),
  e("oly-hang-clean", "Hang Power Clean", "resistance", ["full body", "quads"], "Barbell", "pull"),
  e("oly-split-jerk", "Split Jerk", "resistance", ["shoulders", "quads"], "Barbell", "push"),
  e("oly-clean-pull", "Clean Pull", "resistance", ["back", "hamstrings"], "Barbell", "pull"),
  e("oly-snatch-pull", "Snatch Pull", "resistance", ["back", "hamstrings"], "Barbell", "pull"),
  e("oly-high-pull", "Barbell High Pull", "resistance", ["shoulders", "back"], "Barbell", "pull"),
  e("oly-muscle-snatch", "Muscle Snatch", "resistance", ["shoulders", "back"], "Barbell", "pull"),
  e("oly-ohs-complex", "Snatch Balance", "resistance", ["shoulders", "quads"], "Barbell", "push"),

  // ---------- Dumbbell / hypertrophy isolation ----------
  e("db-fly", "Dumbbell Chest Fly", "resistance", ["chest"], "Dumbbell", "push"),
  e("db-incline-fly", "Incline Dumbbell Fly", "resistance", ["chest"], "Dumbbell", "push"),
  e("db-pullover", "Dumbbell Pullover", "resistance", ["chest", "back"], "Dumbbell", "pull"),
  e("db-arnold-press", "Arnold Press", "resistance", ["shoulders"], "Dumbbell", "push"),
  e("db-front-raise", "Dumbbell Front Raise", "resistance", ["shoulders"], "Dumbbell", "push"),
  e("db-rear-delt-raise", "Bent-Over Rear Delt Raise", "resistance", ["shoulders", "back"], "Dumbbell", "pull"),
  e("db-incline-curl", "Incline Dumbbell Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-concentration-curl", "Concentration Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-preacher-curl", "Preacher Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-overhead-extension", "Overhead Triceps Extension", "resistance", ["triceps"], "Dumbbell", "push"),
  e("db-kickback", "Triceps Kickback", "resistance", ["triceps"], "Dumbbell", "push"),
  e("db-skullcrusher", "Dumbbell Skullcrusher", "resistance", ["triceps"], "Dumbbell", "push"),
  e("db-shrug", "Dumbbell Shrug", "resistance", ["back"], "Dumbbell", "pull"),
  e("db-goblet-curtsy", "Curtsy Lunge", "resistance", ["glutes", "quads"], "Dumbbell", "legs"),
  e("db-reverse-lunge", "Reverse Lunge", "resistance", ["glutes", "quads"], "Dumbbell", "legs"),
  e("db-lateral-lunge", "Lateral Lunge", "resistance", ["glutes", "quads"], "Dumbbell", "legs"),
  e("db-rdl-single", "Single-Leg Romanian Deadlift", "resistance", ["hamstrings", "glutes"], "Dumbbell", "pull"),
  e("db-calf-raise", "Dumbbell Calf Raise", "resistance", ["calves"], "Dumbbell", "legs"),
  e("db-thruster", "Dumbbell Thruster", "resistance", ["shoulders", "quads"], "Dumbbell", "push"),
  e("db-snatch", "Dumbbell Snatch", "resistance", ["full body", "shoulders"], "Dumbbell", "pull"),
  e("db-suitcase-carry", "Suitcase Carry", "resistance", ["core"], "Dumbbell", "core", "time"),
  e("db-renegade-row", "Renegade Row", "resistance", ["back", "core"], "Dumbbell", "pull"),
  e("db-wrist-roller", "Wrist Roller", "resistance", ["biceps"], "Wrist Roller", "pull", "time"),

  // ---------- Kettlebell ----------
  e("kb-snatch", "Kettlebell Snatch", "resistance", ["full body", "shoulders"], "Kettlebell", "pull"),
  e("kb-front-rack-carry", "Front Rack Carry", "resistance", ["core", "shoulders"], "Kettlebell", "core", "time"),
  e("kb-overhead-carry", "Overhead Kettlebell Carry", "resistance", ["shoulders", "core"], "Kettlebell", "core", "time"),
  e("kb-windmill", "Kettlebell Windmill", "resistance", ["core", "shoulders"], "Kettlebell", "core"),
  e("kb-halo", "Kettlebell Halo", "resistance", ["shoulders", "mobility"], "Kettlebell", "mobility", "reps"),
  e("kb-single-swing", "Single-Arm Kettlebell Swing", "resistance", ["glutes", "core"], "Kettlebell", "pull"),

  // ---------- Cable / machine ----------
  e("cbl-fly", "Cable Chest Fly", "resistance", ["chest"], "Cable", "push"),
  e("cbl-low-fly", "Low-to-High Cable Fly", "resistance", ["chest"], "Cable", "push"),
  e("cbl-lateral-raise", "Cable Lateral Raise", "resistance", ["shoulders"], "Cable", "push"),
  e("cbl-rear-delt-fly", "Cable Rear Delt Fly", "resistance", ["shoulders", "back"], "Cable", "pull"),
  e("cbl-straight-arm-pulldown", "Straight-Arm Pulldown", "resistance", ["back"], "Cable", "pull"),
  e("cbl-single-arm-row", "Single-Arm Cable Row", "resistance", ["back"], "Cable", "pull"),
  e("cbl-curl", "Cable Biceps Curl", "resistance", ["biceps"], "Cable", "pull"),
  e("cbl-overhead-extension", "Cable Overhead Extension", "resistance", ["triceps"], "Cable", "push"),
  e("cbl-rope-crunch", "Cable Rope Crunch", "resistance", ["core"], "Cable", "core"),
  e("cbl-kickback-glute", "Cable Glute Kickback", "resistance", ["glutes"], "Cable", "legs"),
  e("cbl-pull-through", "Cable Pull-Through", "resistance", ["glutes", "hamstrings"], "Cable", "pull"),
  e("cbl-anti-rotation-chop", "Half-Kneeling Cable Chop", "resistance", ["core"], "Cable", "core"),
  e("mch-hack-squat", "Hack Squat", "resistance", ["quads"], "Machine", "legs"),
  e("mch-pendulum-squat", "Pendulum Squat", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-smith-squat", "Smith Machine Squat", "resistance", ["quads"], "Machine", "legs"),
  e("mch-belt-squat", "Belt Squat", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-lying-leg-curl", "Lying Leg Curl", "resistance", ["hamstrings"], "Machine", "legs"),
  e("mch-hip-abduction", "Hip Abduction Machine", "resistance", ["glutes"], "Machine", "legs"),
  e("mch-hip-adduction", "Hip Adduction Machine", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-glute-ham-raise", "Glute-Ham Raise", "resistance", ["hamstrings", "glutes"], "GHD", "legs", "reps"),
  e("mch-back-extension", "45° Back Extension", "resistance", ["back", "glutes"], "GHD", "pull", "reps"),
  e("mch-reverse-hyper", "Reverse Hyperextension", "resistance", ["glutes", "back"], "Machine", "pull"),
  e("mch-pec-deck", "Pec Deck", "resistance", ["chest"], "Machine", "push"),
  e("mch-assisted-pullup", "Assisted Pull-Up Machine", "resistance", ["back", "biceps"], "Machine", "pull"),
  e("mch-seated-calf", "Seated Calf Raise", "resistance", ["calves"], "Machine", "legs"),
  e("mch-shoulder-press", "Machine Shoulder Press", "resistance", ["shoulders"], "Machine", "push"),
  e("mch-preacher", "Machine Preacher Curl", "resistance", ["biceps"], "Machine", "pull"),
  e("mch-triceps-dip", "Machine Triceps Dip", "resistance", ["triceps"], "Machine", "push"),
  e("mch-ab-crunch", "Machine Ab Crunch", "resistance", ["core"], "Machine", "core"),
  e("mch-neck-harness", "Neck Harness Extension", "resistance", ["full body"], "Neck Harness", "pull"),
  e("mch-neck-flexion", "Neck Flexion / Extension", "resistance", ["full body"], "Machine", "pull", "reps"),

  // ---------- Bands & strongman ----------
  e("band-face-pull", "Band Face Pull", "resistance", ["shoulders", "back"], "Band", "pull", "reps"),
  e("band-external-rotation", "Band External Rotation", "resistance", ["shoulders"], "Band", "pull", "reps"),
  e("band-lateral-walk", "Banded Lateral Walk", "resistance", ["glutes"], "Band", "legs", "reps"),
  e("band-good-morning", "Banded Good Morning", "resistance", ["hamstrings"], "Band", "pull", "reps"),
  e("band-tricep-pushdown", "Band Triceps Pushdown", "resistance", ["triceps"], "Band", "push", "reps"),
  e("str-yoke-carry", "Yoke Carry", "resistance", ["full body", "core"], "Yoke", "core", "distance"),
  e("str-sandbag-carry", "Sandbag Bear Hug Carry", "resistance", ["core", "full body"], "Sandbag", "core", "distance"),
  e("str-sandbag-clean", "Sandbag Clean over Shoulder", "resistance", ["full body"], "Sandbag", "pull", "reps"),
  e("str-tire-flip", "Tire Flip", "resistance", ["full body", "glutes"], "Tire", "pull", "reps"),
  e("str-log-press", "Log Overhead Press", "resistance", ["shoulders", "triceps"], "Log", "push"),
  e("str-atlas-stone", "Atlas Stone to Shoulder", "resistance", ["full body", "back"], "Stone", "pull", "reps"),
  e("str-sled-drag", "Backward Sled Drag", "resistance", ["quads", "conditioning"], "Sled", "legs", "distance"),

  // ---------- Calisthenics & hypertrophy bodyweight ----------
  e("cal-weighted-pullup", "Weighted Pull-Up", "calisthenics", ["back", "biceps"], "Weight Belt", "pull"),
  e("cal-weighted-dip", "Weighted Dip", "calisthenics", ["chest", "triceps"], "Weight Belt", "push"),
  e("cal-ring-dip", "Ring Dip", "calisthenics", ["chest", "triceps"], "Rings", "push", "reps"),
  e("cal-ring-row", "Ring Row", "calisthenics", ["back", "biceps"], "Rings", "pull", "reps"),
  e("cal-ring-pushup", "Ring Push-Up", "calisthenics", ["chest", "core"], "Rings", "push", "reps"),
  e("cal-ring-support", "Ring Support Hold", "calisthenics", ["shoulders", "core"], "Rings", "core", "time"),
  e("cal-front-lever", "Front Lever Hold", "calisthenics", ["back", "core"], "Bodyweight", "pull", "time"),
  e("cal-back-lever", "Back Lever Hold", "calisthenics", ["back", "chest"], "Bodyweight", "pull", "time"),
  e("cal-planche-lean", "Planche Lean", "calisthenics", ["shoulders", "core"], "Bodyweight", "push", "time"),
  e("cal-tuck-planche", "Tuck Planche", "calisthenics", ["shoulders", "core"], "Bodyweight", "push", "time"),
  e("cal-handstand-hold", "Wall Handstand Hold", "calisthenics", ["shoulders", "core"], "Bodyweight", "push", "time"),
  e("cal-handstand-pushup", "Handstand Push-Up", "calisthenics", ["shoulders", "triceps"], "Bodyweight", "push", "reps"),
  e("cal-explosive-pullup", "Explosive Pull-Up", "calisthenics", ["back"], "Bodyweight", "pull", "reps"),
  e("cal-typewriter-pullup", "Typewriter Pull-Up", "calisthenics", ["back", "biceps"], "Bodyweight", "pull", "reps"),
  e("cal-one-arm-progression", "One-Arm Pull-Up Negative", "calisthenics", ["back", "biceps"], "Bodyweight", "pull", "reps"),
  e("cal-scapular-pullup", "Scapular Pull-Up", "calisthenics", ["back"], "Bodyweight", "pull", "reps"),
  e("cal-dead-hang", "Dead Hang", "calisthenics", ["back", "core"], "Bodyweight", "pull", "time"),
  e("cal-pseudo-planche-pushup", "Pseudo Planche Push-Up", "calisthenics", ["chest", "shoulders"], "Bodyweight", "push", "reps"),
  e("cal-one-arm-pushup", "One-Arm Push-Up", "calisthenics", ["chest", "triceps"], "Bodyweight", "push", "reps"),
  e("cal-hindu-pushup", "Hindu Push-Up", "calisthenics", ["chest", "shoulders"], "Bodyweight", "push", "reps"),
  e("cal-sissy-squat", "Sissy Squat", "calisthenics", ["quads"], "Bodyweight", "legs", "reps"),
  e("cal-shrimp-squat", "Shrimp Squat", "calisthenics", ["quads", "glutes"], "Bodyweight", "legs", "reps"),
  e("cal-jump-squat", "Bodyweight Jump Squat", "calisthenics", ["quads", "glutes"], "Bodyweight", "legs", "reps"),
  e("cal-reverse-nordic", "Reverse Nordic Curl", "calisthenics", ["quads"], "Bodyweight", "legs", "reps"),
  e("cal-single-leg-calf", "Single-Leg Calf Raise", "calisthenics", ["calves"], "Bodyweight", "legs", "reps"),
  e("cal-ab-wheel", "Ab Wheel Rollout", "calisthenics", ["core"], "Ab Wheel", "core", "reps"),
  e("cal-dragon-flag", "Dragon Flag", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-v-up", "V-Up", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-russian-twist", "Russian Twist", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-bicycle-crunch", "Bicycle Crunch", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-mountain-climber", "Mountain Climber", "calisthenics", ["core", "conditioning"], "Bodyweight", "cardio", "time"),
  e("cal-superman", "Superman Hold", "calisthenics", ["back"], "Bodyweight", "core", "time"),
  e("cal-bird-dog", "Bird Dog", "calisthenics", ["core", "back"], "Bodyweight", "core", "reps"),
  e("cal-wall-sit", "Wall Sit", "calisthenics", ["quads"], "Bodyweight", "legs", "time"),
  e("cal-bear-crawl", "Bear Crawl", "calisthenics", ["core", "full body"], "Bodyweight", "cardio", "distance"),
  e("cal-crab-walk", "Crab Walk", "calisthenics", ["core", "triceps"], "Bodyweight", "cardio", "distance"),

  // ---------- Cardio & endurance ----------
  e("car-long-run", "Long Slow Distance Run", "cardio", ["conditioning"], "Outdoor", "cardio", "distance"),
  e("car-fartlek", "Fartlek Run", "cardio", ["conditioning"], "Outdoor", "cardio", "time"),
  e("car-hill-sprint", "Hill Sprints", "cardio", ["quads", "conditioning"], "Outdoor", "cardio", "reps"),
  e("car-stair-run", "Stadium Stair Run", "cardio", ["quads", "conditioning"], "Stairs", "cardio", "reps"),
  e("car-400-repeats", "400m Repeats", "cardio", ["conditioning"], "Track", "cardio", "reps"),
  e("car-800-repeats", "800m Repeats", "cardio", ["conditioning"], "Track", "cardio", "reps"),
  e("car-mile-time-trial", "Mile Time Trial", "cardio", ["conditioning"], "Track", "cardio", "time"),
  e("car-beep-test", "Yo-Yo / Beep Test", "cardio", ["conditioning"], "Court", "cardio", "reps"),
  e("car-ski-erg", "Ski Erg Intervals", "cardio", ["back", "conditioning"], "Machine", "cardio", "time"),
  e("car-stair-climber", "Stair Climber", "cardio", ["quads", "conditioning"], "Machine", "cardio", "time"),
  e("car-elliptical", "Elliptical Steady State", "cardio", ["conditioning"], "Machine", "cardio", "time"),
  e("car-swim-intervals", "Swim Intervals", "cardio", ["full body", "conditioning"], "Pool", "cardio", "reps"),
  e("car-swim-kick", "Kickboard Set", "cardio", ["quads", "conditioning"], "Pool", "cardio", "distance"),
  e("car-battle-ropes", "Battle Ropes", "cardio", ["shoulders", "conditioning"], "Battle Ropes", "cardio", "time"),
  e("car-farmers-medley", "Conditioning Carry Medley", "cardio", ["full body", "conditioning"], "Mixed", "cardio", "time"),
  e("car-boxing-rounds", "Heavy Bag Rounds", "cardio", ["shoulders", "conditioning"], "Heavy Bag", "cardio", "time"),
  e("car-shadow-boxing", "Shadow Boxing", "cardio", ["conditioning"], "Bodyweight", "cardio", "time"),
  e("car-rucking", "Weighted Ruck", "cardio", ["conditioning", "core"], "Ruck", "cardio", "distance"),
  e("car-tabata", "Tabata Circuit", "cardio", ["conditioning", "full body"], "Bodyweight", "cardio", "time"),
  e("car-emom-conditioning", "EMOM Conditioning", "cardio", ["conditioning"], "Mixed", "cardio", "time"),

  // ---------- Athletic / sport skill ----------
  e("ath-qb-dropback", "QB 3/5/7-Step Dropbacks", "athletic", ["conditioning", "quads"], "Football", "cardio", "reps"),
  e("ath-qb-throw-net", "QB Accuracy Net Throws", "athletic", ["shoulders", "core"], "Football", "core", "reps"),
  e("ath-qb-rollout-throw", "QB Rollout Throws", "athletic", ["core", "shoulders"], "Football", "core", "reps"),
  e("ath-qb-footwork-ladder", "QB Quick-Feet Ladder", "athletic", ["conditioning"], "Agility Ladder", "cardio", "reps"),
  e("ath-wr-route-tree", "WR Route Tree Reps", "athletic", ["conditioning", "quads"], "Football", "cardio", "reps"),
  e("ath-wr-release-drill", "WR Press Release Drill", "athletic", ["conditioning"], "Football", "cardio", "reps"),
  e("ath-wr-hands-jugs", "Jugs Machine Catches", "athletic", ["conditioning"], "Jugs Machine", "cardio", "reps"),
  e("ath-wr-high-point", "High-Point Catch Drill", "athletic", ["calves", "core"], "Football", "legs", "reps"),
  e("ath-db-backpedal", "Backpedal & Flip Drill", "athletic", ["conditioning", "glutes"], "Cones", "cardio", "reps"),
  e("ath-lineman-sled", "Blocking Sled Drive", "athletic", ["quads", "chest"], "Sled", "push", "reps"),
  e("ath-cricket-shadow-bat", "Cricket Shadow Batting", "athletic", ["core", "shoulders"], "Cricket Bat", "core", "reps"),
  e("ath-cricket-throwdowns", "Throwdown Batting Reps", "athletic", ["core", "conditioning"], "Cricket Bat", "core", "reps"),
  e("ath-cricket-footwork", "Batting Footwork Drill", "athletic", ["quads", "conditioning"], "Cricket Bat", "cardio", "reps"),
  e("ath-cricket-running-3s", "Running Between Wickets 3s", "athletic", ["conditioning"], "Cricket Pitch", "cardio", "reps"),
  e("ath-cricket-bowling-run", "Bowling Run-Up Repeats", "athletic", ["conditioning", "shoulders"], "Cricket Pitch", "cardio", "reps"),
  e("ath-cricket-fielding", "Ground Fielding & Throw", "athletic", ["conditioning", "core"], "Cricket Ball", "cardio", "reps"),
  e("ath-basketball-shooting", "Spot Shooting Reps", "athletic", ["shoulders", "conditioning"], "Basketball", "cardio", "reps"),
  e("ath-basketball-handles", "Two-Ball Handling Series", "athletic", ["conditioning"], "Basketball", "cardio", "time"),
  e("ath-basketball-defslide", "Defensive Slide Drill", "athletic", ["glutes", "quads"], "Court", "cardio", "time"),
  e("ath-soccer-rondo", "Rondo Possession", "athletic", ["conditioning"], "Soccer Ball", "cardio", "time"),
  e("ath-soccer-finishing", "Finishing Reps", "athletic", ["quads", "conditioning"], "Soccer Ball", "cardio", "reps"),
  e("ath-tennis-serve", "Serve Basket Reps", "athletic", ["shoulders", "core"], "Racquet", "core", "reps"),
  e("ath-tennis-split-step", "Split-Step Reaction Drill", "athletic", ["calves", "conditioning"], "Court", "cardio", "reps"),
  e("ath-volleyball-approach", "Spike Approach Jumps", "athletic", ["quads", "calves"], "Volleyball", "legs", "reps"),
  e("ath-volleyball-blocking", "Blocking Footwork", "athletic", ["quads", "conditioning"], "Court", "cardio", "reps"),
  e("ath-swim-starts", "Block Starts", "athletic", ["quads", "conditioning"], "Pool", "legs", "reps"),
  e("ath-wrestling-shots", "Penetration Step Shots", "athletic", ["quads", "conditioning"], "Mat", "cardio", "reps"),
  e("ath-wrestling-bridge", "Neck Bridge Hold", "athletic", ["full body", "core"], "Mat", "core", "time"),
  e("ath-hockey-crossovers", "Crossover Skating Drill", "athletic", ["glutes", "quads"], "Ice", "cardio", "reps"),
  e("ath-golf-med-ball", "Golf Rotational Throw", "athletic", ["core"], "Med Ball", "core", "reps"),
  e("ath-track-block-start", "Sprint Block Starts", "athletic", ["quads", "conditioning"], "Track", "cardio", "reps"),
  e("ath-track-wicket", "Wicket Runs", "athletic", ["hamstrings", "conditioning"], "Track", "cardio", "reps"),
  e("ath-sled-sprint", "Resisted Sled Sprint", "athletic", ["quads", "glutes"], "Sled", "cardio", "reps"),
  e("ath-band-resisted-sprint", "Band-Resisted Sprint", "athletic", ["quads", "glutes"], "Band", "cardio", "reps"),
  e("ath-reaction-ball", "Reaction Ball Drill", "athletic", ["conditioning"], "Reaction Ball", "cardio", "reps"),
  e("ath-hurdle-hops", "Hurdle Hops", "athletic", ["calves", "quads"], "Hurdles", "legs", "reps"),
  e("ath-single-leg-box-jump", "Single-Leg Box Jump", "athletic", ["quads", "glutes"], "Plyo Box", "legs", "reps"),
  e("ath-tuck-jump", "Tuck Jump", "athletic", ["quads", "core"], "Bodyweight", "legs", "reps"),
  e("ath-mb-scoop-toss", "Med Ball Scoop Toss", "athletic", ["glutes", "core"], "Med Ball", "core", "reps"),
  e("ath-mb-shotput", "Med Ball Shot-Put Throw", "athletic", ["chest", "core"], "Med Ball", "push", "reps"),
  e("ath-lateral-hurdle-hop", "Lateral Hurdle Hop", "athletic", ["glutes", "calves"], "Hurdles", "legs", "reps"),
  e("ath-dot-drill", "Dot Drill", "athletic", ["calves", "conditioning"], "Bodyguard", "cardio", "reps"),
  e("ath-mirror-drill", "Partner Mirror Drill", "athletic", ["conditioning"], "Cones", "cardio", "time"),

  // ---------- Recovery / mobility / prehab ----------
  e("rec-pigeon", "Pigeon Pose", "recovery", ["mobility", "glutes"], "Bodyweight", "mobility", "time"),
  e("rec-frog", "Frog Stretch", "recovery", ["mobility", "glutes"], "Bodyweight", "mobility", "time"),
  e("rec-jefferson-curl", "Jefferson Curl", "recovery", ["mobility", "hamstrings"], "Dumbbell", "mobility", "reps"),
  e("rec-cossack", "Cossack Squat", "recovery", ["mobility", "quads"], "Bodyweight", "mobility", "reps"),
  e("rec-deep-squat-hold", "Deep Squat Hold", "recovery", ["mobility", "glutes"], "Bodyweight", "mobility", "time"),
  e("rec-childs-pose", "Child's Pose", "recovery", ["mobility", "back"], "Bodyweight", "mobility", "time"),
  e("rec-downdog", "Downward Dog", "recovery", ["mobility", "hamstrings"], "Bodyweight", "mobility", "time"),
  e("rec-couch-band-distraction", "Banded Hip Distraction", "recovery", ["mobility", "glutes"], "Band", "mobility", "time"),
  e("rec-scap-pushup", "Scapular Push-Up", "recovery", ["shoulders", "mobility"], "Bodyweight", "mobility", "reps"),
  e("rec-wall-slide", "Wall Slide", "recovery", ["shoulders", "mobility"], "Bodyweight", "mobility", "reps"),
  e("rec-yttw", "Y-T-W Raises", "recovery", ["shoulders", "back"], "Dumbbell", "mobility", "reps"),
  e("rec-tibialis-raise", "Tibialis Raise", "recovery", ["calves", "mobility"], "Bodyweight", "mobility", "reps"),
  e("rec-calf-stretch", "Wall Calf Stretch", "recovery", ["calves", "mobility"], "Bodyweight", "mobility", "time"),
  e("rec-neck-cars", "Neck CARs", "recovery", ["mobility"], "Bodyweight", "mobility", "reps"),
  e("rec-thoracic-extension", "Foam Roller Thoracic Extension", "recovery", ["mobility", "back"], "Foam Roller", "mobility", "reps"),
  e("rec-lacrosse-foot", "Plantar Fascia Ball Roll", "recovery", ["mobility", "calves"], "Massage Ball", "mobility", "time"),
  e("rec-contrast-shower", "Contrast Shower Protocol", "recovery", ["mobility"], "None", "mobility", "time"),
  e("rec-nsdr", "NSDR / Yoga Nidra", "recovery", ["mobility"], "None", "mobility", "time"),
  e("rec-easy-swim", "Easy Recovery Swim", "recovery", ["conditioning", "mobility"], "Pool", "mobility", "time"),
  e("rec-bike-flush", "Recovery Spin", "recovery", ["conditioning", "mobility"], "Bike", "mobility", "time"),
];
