import type { Exercise, ExerciseCategory } from "./types";

const e = (
  id: string,
  name: string,
  category: ExerciseCategory,
  muscles: Exercise["muscles"],
  equipment: string,
  pattern: Exercise["pattern"],
  metric: Exercise["metric"] = "weight_reps",
): Exercise => ({ id, name, category, muscles, equipment, pattern, metric });

/**
 * Fourth wave: sport-specific drills for every major sport plus the machine /
 * Smith / specialty gym variations athletes ask for by name.
 */
export const SPORT_EXERCISES: Exercise[] = [
  // ---------- Smith machine & machine strength ----------
  e("sm-incline-press", "Incline Smith Machine Press", "resistance", ["chest", "shoulders"], "Smith Machine", "push"),
  e("sm-flat-press", "Flat Smith Machine Bench Press", "resistance", ["chest", "triceps"], "Smith Machine", "push"),
  e("sm-decline-press", "Decline Smith Machine Press", "resistance", ["chest"], "Smith Machine", "push"),
  e("sm-shoulder-press", "Smith Machine Shoulder Press", "resistance", ["shoulders", "triceps"], "Smith Machine", "push"),
  e("sm-back-squat", "Smith Machine Back Squat", "resistance", ["quads", "glutes"], "Smith Machine", "legs"),
  e("sm-front-squat", "Smith Machine Front Squat", "resistance", ["quads"], "Smith Machine", "legs"),
  e("sm-split-squat", "Smith Machine Split Squat", "resistance", ["quads", "glutes"], "Smith Machine", "legs"),
  e("sm-hip-thrust", "Smith Machine Hip Thrust", "resistance", ["glutes", "hamstrings"], "Smith Machine", "legs"),
  e("sm-row", "Smith Machine Bent-Over Row", "resistance", ["back", "biceps"], "Smith Machine", "pull"),
  e("sm-shrug", "Smith Machine Shrug", "resistance", ["back", "shoulders"], "Smith Machine", "pull"),
  e("sm-calf-raise", "Smith Machine Calf Raise", "resistance", ["calves"], "Smith Machine", "legs"),
  e("sm-rdl", "Smith Machine Romanian Deadlift", "resistance", ["hamstrings", "glutes"], "Smith Machine", "pull"),
  e("mch-incline-press", "Machine Incline Chest Press", "resistance", ["chest", "shoulders"], "Machine", "push"),
  e("mch-pec-deck", "Pec Deck Fly", "resistance", ["chest"], "Machine", "push"),
  e("mch-shoulder-press", "Machine Shoulder Press", "resistance", ["shoulders", "triceps"], "Machine", "push"),
  e("mch-lateral-raise", "Machine Lateral Raise", "resistance", ["shoulders"], "Machine", "push"),
  e("mch-triceps-dip", "Machine Triceps Dip", "resistance", ["triceps", "chest"], "Machine", "push"),
  e("mch-assisted-pullup", "Assisted Pull-Up Machine", "resistance", ["back", "biceps"], "Machine", "pull"),
  e("mch-t-bar-row", "T-Bar Row", "resistance", ["back", "biceps"], "Machine", "pull"),
  e("mch-chest-supported-row", "Chest-Supported Row", "resistance", ["back", "biceps"], "Machine", "pull"),
  e("mch-hack-squat", "Hack Squat", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-pendulum-squat", "Pendulum Squat", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-belt-squat", "Belt Squat", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-lying-leg-curl", "Lying Leg Curl", "resistance", ["hamstrings"], "Machine", "legs"),
  e("mch-hip-abduction", "Hip Abduction Machine", "resistance", ["glutes"], "Machine", "legs"),
  e("mch-hip-adduction", "Hip Adduction Machine", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-glute-kickback", "Machine Glute Kickback", "resistance", ["glutes"], "Machine", "legs"),
  e("mch-seated-calf", "Seated Calf Raise", "resistance", ["calves"], "Machine", "legs"),
  e("mch-back-extension", "45° Back Extension", "resistance", ["back", "glutes"], "Machine", "pull", "reps"),
  e("mch-ab-crunch", "Machine Ab Crunch", "resistance", ["core"], "Machine", "core"),
  e("mch-torso-rotation", "Machine Torso Rotation", "resistance", ["core"], "Machine", "core"),
  e("mch-neck-extension", "Neck Harness Extension", "resistance", ["back"], "Machine", "pull"),
  e("mch-neck-flexion", "Neck Flexion", "resistance", ["core"], "Machine", "core"),
  e("cbl-upright-row", "Cable Upright Row", "resistance", ["shoulders"], "Cable", "pull"),
  e("cbl-crossover", "Cable Crossover", "resistance", ["chest"], "Cable", "push"),
  e("cbl-low-fly", "Low-to-High Cable Fly", "resistance", ["chest"], "Cable", "push"),
  e("cbl-straight-arm-pulldown", "Straight-Arm Pulldown", "resistance", ["back"], "Cable", "pull"),
  e("cbl-kneeling-crunch", "Cable Kneeling Crunch", "resistance", ["core"], "Cable", "core"),
  e("cbl-pull-through", "Cable Pull-Through", "resistance", ["glutes", "hamstrings"], "Cable", "pull"),
  e("cbl-lateral-raise", "Cable Lateral Raise", "resistance", ["shoulders"], "Cable", "push"),
  e("hex-bar-deadlift", "Trap Bar Deadlift", "resistance", ["quads", "glutes", "back"], "Trap Bar", "pull"),
  e("hex-bar-jump", "Trap Bar Jump", "athletic", ["quads", "glutes"], "Trap Bar", "legs", "reps"),
  e("bb-deficit-deadlift", "Deficit Deadlift", "resistance", ["hamstrings", "back"], "Barbell", "pull"),
  e("bb-rack-pull", "Rack Pull", "resistance", ["back", "hamstrings"], "Barbell", "pull"),
  e("bb-pause-squat", "Pause Back Squat", "resistance", ["quads", "glutes"], "Barbell", "legs"),
  e("bb-box-squat", "Box Squat", "resistance", ["glutes", "quads"], "Barbell", "legs"),
  e("bb-good-morning", "Good Morning", "resistance", ["hamstrings", "back"], "Barbell", "pull"),
  e("bb-zercher-squat", "Zercher Squat", "resistance", ["quads", "core"], "Barbell", "legs"),
  e("bb-landmine-press", "Landmine Press", "resistance", ["shoulders", "chest"], "Landmine", "push"),
  e("bb-landmine-row", "Landmine Row", "resistance", ["back"], "Landmine", "pull"),
  e("bb-landmine-rotation", "Landmine Rotation", "resistance", ["core"], "Landmine", "core", "reps"),
  e("bb-floor-press", "Barbell Floor Press", "resistance", ["chest", "triceps"], "Barbell", "push"),
  e("bb-spoto-press", "Spoto Press", "resistance", ["chest", "triceps"], "Barbell", "push"),
  e("bb-pin-press", "Pin Press", "resistance", ["chest", "shoulders"], "Barbell", "push"),
  e("bb-clean-pull", "Clean Pull", "resistance", ["back", "glutes"], "Barbell", "pull"),
  e("bb-snatch-pull", "Snatch Pull", "resistance", ["back", "glutes"], "Barbell", "pull"),
  e("bb-push-jerk", "Push Jerk", "resistance", ["shoulders", "quads"], "Barbell", "push"),
  e("bb-split-jerk", "Split Jerk", "resistance", ["shoulders", "quads"], "Barbell", "push"),
  e("bb-thruster", "Barbell Thruster", "resistance", ["quads", "shoulders"], "Barbell", "push"),
  e("bb-overhead-squat", "Overhead Squat", "resistance", ["quads", "shoulders"], "Barbell", "legs"),
  e("db-arnold-press", "Arnold Press", "resistance", ["shoulders"], "Dumbbell", "push"),
  e("db-pullover", "Dumbbell Pullover", "resistance", ["chest", "back"], "Dumbbell", "push"),
  e("db-fly", "Dumbbell Chest Fly", "resistance", ["chest"], "Dumbbell", "push"),
  e("db-rear-delt-fly", "Dumbbell Rear Delt Fly", "resistance", ["shoulders", "back"], "Dumbbell", "pull"),
  e("db-front-raise", "Dumbbell Front Raise", "resistance", ["shoulders"], "Dumbbell", "push"),
  e("db-shrug", "Dumbbell Shrug", "resistance", ["back", "shoulders"], "Dumbbell", "pull"),
  e("db-single-leg-rdl", "Single-Leg Romanian Deadlift", "resistance", ["hamstrings", "glutes"], "Dumbbell", "legs"),
  e("db-reverse-lunge", "Dumbbell Reverse Lunge", "resistance", ["quads", "glutes"], "Dumbbell", "legs"),
  e("db-lateral-lunge", "Lateral Lunge", "resistance", ["glutes", "quads"], "Dumbbell", "legs"),
  e("db-curtsy-lunge", "Curtsy Lunge", "resistance", ["glutes"], "Dumbbell", "legs"),
  e("db-suitcase-carry", "Suitcase Carry", "resistance", ["core"], "Dumbbell", "core", "time"),
  e("kb-front-rack-carry", "Front Rack Carry", "resistance", ["core", "shoulders"], "Kettlebell", "core", "time"),
  e("kb-snatch", "Kettlebell Snatch", "resistance", ["full body", "shoulders"], "Kettlebell", "pull", "reps"),
  e("kb-windmill", "Kettlebell Windmill", "resistance", ["core", "shoulders"], "Kettlebell", "core", "reps"),

  // ---------- Extra calisthenics / push-up family ----------
  e("cal-knee-pushup", "Knee Push-Up", "calisthenics", ["chest", "triceps"], "Bodyweight", "push", "reps"),
  e("cal-incline-pushup", "Incline Push-Up", "calisthenics", ["chest"], "Bodyweight", "push", "reps"),
  e("cal-wide-pushup", "Wide-Grip Push-Up", "calisthenics", ["chest"], "Bodyweight", "push", "reps"),
  e("cal-close-pushup", "Close-Grip Push-Up", "calisthenics", ["triceps"], "Bodyweight", "push", "reps"),
  e("cal-clap-pushup", "Clap Push-Up", "calisthenics", ["chest", "triceps"], "Bodyweight", "push", "reps"),
  e("cal-spiderman-pushup", "Spiderman Push-Up", "calisthenics", ["chest", "core"], "Bodyweight", "push", "reps"),
  e("cal-hindu-pushup", "Hindu Push-Up", "calisthenics", ["chest", "shoulders"], "Bodyweight", "push", "reps"),
  e("cal-handstand-pushup", "Handstand Push-Up", "calisthenics", ["shoulders", "triceps"], "Bodyweight", "push", "reps"),
  e("cal-weighted-pushup", "Weighted Push-Up", "calisthenics", ["chest", "triceps"], "Weight Plate", "push"),
  e("cal-ring-pushup", "Ring Push-Up", "calisthenics", ["chest", "core"], "Rings", "push", "reps"),
  e("cal-pseudo-planche-pushup", "Pseudo Planche Push-Up", "calisthenics", ["chest", "shoulders"], "Bodyweight", "push", "reps"),
  e("cal-one-arm-pushup", "One-Arm Push-Up", "calisthenics", ["chest", "triceps"], "Bodyweight", "push", "reps"),
  e("cal-ring-row", "Ring Row", "calisthenics", ["back", "biceps"], "Rings", "pull", "reps"),
  e("cal-ring-dip", "Ring Dip", "calisthenics", ["chest", "triceps"], "Rings", "push", "reps"),
  e("cal-front-lever", "Front Lever Hold", "calisthenics", ["back", "core"], "Bodyweight", "pull", "time"),
  e("cal-back-lever", "Back Lever Hold", "calisthenics", ["back", "core"], "Bodyweight", "pull", "time"),
  e("cal-tuck-planche", "Tuck Planche Hold", "calisthenics", ["shoulders", "core"], "Bodyweight", "push", "time"),
  e("cal-handstand-hold", "Handstand Hold", "calisthenics", ["shoulders", "core"], "Bodyweight", "push", "time"),
  e("cal-wall-sit", "Wall Sit", "calisthenics", ["quads"], "Bodyweight", "legs", "time"),
  e("cal-shrimp-squat", "Shrimp Squat", "calisthenics", ["quads", "glutes"], "Bodyweight", "legs", "reps"),
  e("cal-jump-squat", "Bodyweight Jump Squat", "calisthenics", ["quads", "glutes"], "Bodyweight", "legs", "reps"),
  e("cal-mountain-climber", "Mountain Climbers", "calisthenics", ["core", "conditioning"], "Bodyweight", "core", "time"),
  e("cal-bicycle-crunch", "Bicycle Crunch", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-russian-twist", "Russian Twist", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-v-up", "V-Up", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-flutter-kick", "Flutter Kicks", "calisthenics", ["core"], "Bodyweight", "core", "time"),
  e("cal-superman", "Superman Hold", "calisthenics", ["back"], "Bodyweight", "core", "time"),
  e("cal-bear-crawl", "Bear Crawl", "calisthenics", ["core", "conditioning"], "Bodyweight", "core", "distance"),
  e("cal-crab-walk", "Crab Walk", "calisthenics", ["core", "triceps"], "Bodyweight", "core", "distance"),

  // ---------- Football drills ----------
  e("fb-40-start", "Football — 40-Yard Start Stance Take-Off", "athletic", ["conditioning", "quads"], "Field", "cardio", "reps"),
  e("fb-3cone", "Football — 3-Cone (L) Drill", "athletic", ["conditioning"], "Cones", "cardio", "reps"),
  e("fb-w-drill", "Football — W Agility Drill", "athletic", ["conditioning"], "Cones", "cardio", "reps"),
  e("fb-qb-dropback", "QB — 3/5/7 Step Dropbacks", "athletic", ["conditioning", "core"], "Field", "cardio", "reps"),
  e("fb-qb-throw-on-run", "QB — Throw on the Run", "athletic", ["core", "shoulders"], "Football", "cardio", "reps"),
  e("fb-qb-pocket-slide", "QB — Pocket Slide & Reset", "athletic", ["conditioning", "quads"], "Field", "cardio", "reps"),
  e("fb-qb-footfire", "QB — Foot Fire Quick Release", "athletic", ["conditioning"], "Football", "cardio", "time"),
  e("fb-wr-release", "WR — Press Release Drill", "athletic", ["conditioning"], "Field", "cardio", "reps"),
  e("fb-wr-routetree", "WR — Route Tree Reps", "athletic", ["conditioning"], "Cones", "cardio", "reps"),
  e("fb-wr-catch-hands", "WR — Hands Catching Drill", "athletic", ["conditioning"], "Football", "cardio", "reps"),
  e("fb-wr-sideline-toe-tap", "WR — Sideline Toe-Tap Catch", "athletic", ["core"], "Football", "cardio", "reps"),
  e("fb-rb-cut", "RB — Jump Cut Cone Drill", "athletic", ["quads", "conditioning"], "Cones", "cardio", "reps"),
  e("fb-rb-ball-security", "RB — Ball Security Gauntlet", "athletic", ["conditioning"], "Football", "cardio", "reps"),
  e("fb-db-backpedal", "DB — Backpedal & Break", "athletic", ["conditioning", "hamstrings"], "Cones", "cardio", "reps"),
  e("fb-db-hip-flip", "DB — Hip Flip Turn Drill", "athletic", ["glutes", "conditioning"], "Field", "cardio", "reps"),
  e("fb-lb-shuffle-fill", "LB — Shuffle & Fill", "athletic", ["conditioning"], "Cones", "cardio", "reps"),
  e("fb-ol-pass-set", "OL — Kick-Slide Pass Set", "athletic", ["quads", "glutes"], "Field", "cardio", "reps"),
  e("fb-dl-getoff", "DL — Get-Off & Rip", "athletic", ["conditioning", "shoulders"], "Field", "cardio", "reps"),
  e("fb-sled-drive", "Football — Blocking Sled Drive", "athletic", ["quads", "conditioning"], "Sled", "cardio", "reps"),
  e("fb-gassers", "Football — Gassers", "cardio", ["conditioning"], "Field", "cardio", "reps"),
  e("fb-tackle-form", "Football — Form Tackling Drill", "athletic", ["full body"], "Field", "cardio", "reps"),

  // ---------- Soccer drills ----------
  e("soc-cone-dribble", "Soccer — Cone Dribbling Slalom", "athletic", ["conditioning"], "Soccer Ball", "cardio", "time"),
  e("soc-toe-taps", "Soccer — Ball Toe Taps", "athletic", ["conditioning", "calves"], "Soccer Ball", "cardio", "time"),
  e("soc-inside-outside", "Soccer — Inside/Outside Touches", "athletic", ["conditioning"], "Soccer Ball", "cardio", "time"),
  e("soc-wall-passing", "Soccer — Wall Passing Reps", "athletic", ["conditioning"], "Soccer Ball", "cardio", "reps"),
  e("soc-first-touch", "Soccer — First Touch Control", "athletic", ["conditioning"], "Soccer Ball", "cardio", "reps"),
  e("soc-shooting", "Soccer — Finishing Reps", "athletic", ["quads", "conditioning"], "Soccer Ball", "cardio", "reps"),
  e("soc-1v1", "Soccer — 1v1 Take-On Drill", "athletic", ["conditioning"], "Soccer Ball", "cardio", "reps"),
  e("soc-header", "Soccer — Heading Practice", "athletic", ["core"], "Soccer Ball", "cardio", "reps"),
  e("soc-yoyo", "Soccer — Yo-Yo Intermittent Test", "cardio", ["conditioning"], "Field", "cardio", "time"),
  e("soc-repeat-sprint", "Soccer — Repeated Sprint Ability", "cardio", ["conditioning"], "Field", "cardio", "reps"),
  e("soc-keeper-dive", "Goalkeeper — Diving Save Reps", "athletic", ["full body"], "Soccer Ball", "cardio", "reps"),
  e("soc-keeper-footwork", "Goalkeeper — Lateral Footwork", "athletic", ["conditioning"], "Cones", "cardio", "time"),

  // ---------- Basketball ----------
  e("bkb-form-shooting", "Basketball — Form Shooting", "athletic", ["shoulders"], "Basketball", "cardio", "reps"),
  e("bkb-spot-shooting", "Basketball — 5-Spot Shooting", "athletic", ["conditioning"], "Basketball", "cardio", "reps"),
  e("bkb-free-throws", "Basketball — Free Throw Reps", "athletic", ["shoulders"], "Basketball", "cardio", "reps"),
  e("bkb-mikan", "Basketball — Mikan Drill", "athletic", ["conditioning"], "Basketball", "cardio", "reps"),
  e("bkb-two-ball-dribble", "Basketball — Two-Ball Dribbling", "athletic", ["conditioning"], "Basketball", "cardio", "time"),
  e("bkb-crossover-series", "Basketball — Crossover Series", "athletic", ["conditioning"], "Basketball", "cardio", "time"),
  e("bkb-defensive-slide", "Basketball — Defensive Slides", "athletic", ["quads", "glutes"], "Court", "cardio", "time"),
  e("bkb-closeout", "Basketball — Closeout Drill", "athletic", ["conditioning"], "Court", "cardio", "reps"),
  e("bkb-rebound-tap", "Basketball — Rebound Tap Drill", "athletic", ["calves", "shoulders"], "Basketball", "cardio", "reps"),
  e("bkb-transition-sprint", "Basketball — Transition Sprints", "cardio", ["conditioning"], "Court", "cardio", "reps"),

  // ---------- Baseball / softball ----------
  e("bsb-tee-work", "Baseball — Tee Work", "athletic", ["core"], "Bat", "cardio", "reps"),
  e("bsb-soft-toss", "Baseball — Soft Toss", "athletic", ["core"], "Bat", "cardio", "reps"),
  e("bsb-front-toss", "Baseball — Front Toss BP", "athletic", ["core"], "Bat", "cardio", "reps"),
  e("bsb-long-toss", "Baseball — Long Toss", "athletic", ["shoulders"], "Baseball", "cardio", "reps"),
  e("bsb-pitch-bullpen", "Baseball — Bullpen Session", "athletic", ["shoulders", "core"], "Baseball", "cardio", "reps"),
  e("bsb-plyo-ball-throw", "Baseball — Plyo Ball Throws", "athletic", ["shoulders", "core"], "Plyo Ball", "cardio", "reps"),
  e("bsb-jaeger-bands", "Baseball — J-Band Arm Care", "recovery", ["shoulders", "mobility"], "Band", "mobility", "reps"),
  e("bsb-infield-groundballs", "Baseball — Infield Ground Balls", "athletic", ["conditioning"], "Baseball", "cardio", "reps"),
  e("bsb-outfield-flyballs", "Baseball — Outfield Fly Balls", "athletic", ["conditioning"], "Baseball", "cardio", "reps"),
  e("bsb-base-stealing", "Baseball — Base Stealing Jumps", "athletic", ["quads", "conditioning"], "Field", "cardio", "reps"),
  e("sfb-slap-hitting", "Softball — Slap Hitting Reps", "athletic", ["core"], "Bat", "cardio", "reps"),
  e("sfb-windmill-pitch", "Softball — Windmill Pitching", "athletic", ["shoulders", "core"], "Softball", "cardio", "reps"),

  // ---------- Cricket ----------
  e("crk-batting-throwdowns", "Cricket — Batting Throwdowns", "athletic", ["core"], "Cricket Bat", "cardio", "reps"),
  e("crk-shadow-batting", "Cricket — Shadow Batting", "athletic", ["core"], "Cricket Bat", "cardio", "time"),
  e("crk-front-foot-drive", "Cricket — Front Foot Drive Reps", "athletic", ["core", "quads"], "Cricket Bat", "cardio", "reps"),
  e("crk-pull-shot", "Cricket — Pull Shot Reps", "athletic", ["core"], "Cricket Bat", "cardio", "reps"),
  e("crk-fast-bowling", "Cricket — Fast Bowling Spell", "athletic", ["shoulders", "conditioning"], "Cricket Ball", "cardio", "reps"),
  e("crk-spin-bowling", "Cricket — Spin Bowling Reps", "athletic", ["shoulders"], "Cricket Ball", "cardio", "reps"),
  e("crk-run-between-wickets", "Cricket — Running Between Wickets", "cardio", ["conditioning"], "Field", "cardio", "reps"),
  e("crk-slip-catching", "Cricket — Slip Catching", "athletic", ["conditioning"], "Cricket Ball", "cardio", "reps"),
  e("crk-fielding-throws", "Cricket — Fielding Pick-Up & Throw", "athletic", ["shoulders", "conditioning"], "Cricket Ball", "cardio", "reps"),

  // ---------- Volleyball ----------
  e("vb-approach-jump", "Volleyball — Spike Approach Jumps", "athletic", ["quads", "calves"], "Court", "legs", "reps"),
  e("vb-blocking-footwork", "Volleyball — Blocking Footwork", "athletic", ["quads", "conditioning"], "Court", "cardio", "reps"),
  e("vb-serve-reps", "Volleyball — Serving Reps", "athletic", ["shoulders", "core"], "Volleyball", "cardio", "reps"),
  e("vb-passing-platform", "Volleyball — Passing Platform Reps", "athletic", ["conditioning"], "Volleyball", "cardio", "reps"),
  e("vb-setting-reps", "Volleyball — Setting Reps", "athletic", ["shoulders"], "Volleyball", "cardio", "reps"),
  e("vb-dig-shuffle", "Volleyball — Dig & Shuffle Drill", "athletic", ["conditioning"], "Court", "cardio", "time"),
  e("vb-pepper", "Volleyball — Pepper Drill", "athletic", ["conditioning"], "Volleyball", "cardio", "time"),

  // ---------- Tennis / racquet ----------
  e("tn-forehand-basket", "Tennis — Forehand Basket Drill", "athletic", ["core", "shoulders"], "Racquet", "cardio", "reps"),
  e("tn-backhand-basket", "Tennis — Backhand Basket Drill", "athletic", ["core", "shoulders"], "Racquet", "cardio", "reps"),
  e("tn-serve-reps", "Tennis — Serve Reps", "athletic", ["shoulders", "core"], "Racquet", "cardio", "reps"),
  e("tn-split-step", "Tennis — Split Step Reaction", "athletic", ["calves", "conditioning"], "Court", "cardio", "reps"),
  e("tn-suicide-court", "Tennis — Sideline Suicides", "cardio", ["conditioning"], "Court", "cardio", "reps"),
  e("bd-shadow-badminton", "Badminton — Shadow Footwork", "athletic", ["conditioning"], "Court", "cardio", "time"),
  e("pkl-dink-drill", "Pickleball — Dink Control Drill", "athletic", ["conditioning"], "Paddle", "cardio", "time"),

  // ---------- Track & field ----------
  e("trk-block-starts", "Track — Block Starts", "athletic", ["quads", "glutes"], "Track", "cardio", "reps"),
  e("trk-acceleration-wall", "Track — Wall Acceleration Drill", "athletic", ["quads", "conditioning"], "Wall", "cardio", "reps"),
  e("trk-bskips", "Track — B-Skips", "athletic", ["hamstrings", "conditioning"], "Track", "cardio", "reps"),
  e("trk-straight-leg-bound", "Track — Straight-Leg Bounds", "athletic", ["hamstrings", "calves"], "Track", "cardio", "reps"),
  e("trk-hurdle-mobility", "Track — Hurdle Mobility Walkovers", "recovery", ["mobility", "glutes"], "Hurdles", "mobility", "reps"),
  e("trk-hurdle-3step", "Track — 3-Step Hurdle Rhythm", "athletic", ["conditioning"], "Hurdles", "cardio", "reps"),
  e("trk-shot-put-glide", "Track — Shot Put Glide Reps", "athletic", ["full body", "shoulders"], "Shot", "cardio", "reps"),
  e("trk-discus-throw", "Track — Discus Throw Reps", "athletic", ["core", "shoulders"], "Discus", "cardio", "reps"),
  e("trk-javelin-throw", "Track — Javelin Throw Reps", "athletic", ["shoulders", "core"], "Javelin", "cardio", "reps"),
  e("trk-long-jump-approach", "Track — Long Jump Approach", "athletic", ["quads", "conditioning"], "Track", "cardio", "reps"),
  e("trk-high-jump-approach", "Track — High Jump Curve Approach", "athletic", ["calves", "quads"], "Track", "cardio", "reps"),
  e("trk-pole-vault-run", "Track — Pole Vault Run-Through", "athletic", ["conditioning"], "Track", "cardio", "reps"),
  e("trk-400-repeats", "Track — 400m Repeats", "cardio", ["conditioning"], "Track", "cardio", "reps"),
  e("trk-200-repeats", "Track — 200m Repeats", "cardio", ["conditioning"], "Track", "cardio", "reps"),
  e("trk-hill-sprints", "Hill Sprints", "cardio", ["quads", "conditioning"], "Outdoor", "cardio", "reps"),
  e("trk-parachute-sprint", "Resisted Parachute Sprint", "athletic", ["quads", "conditioning"], "Parachute", "cardio", "reps"),
  e("trk-band-resisted-sprint", "Band-Resisted Sprint Start", "athletic", ["glutes", "quads"], "Band", "cardio", "reps"),

  // ---------- Swimming / water ----------
  e("swm-kick-set", "Swimming — Kick Board Set", "cardio", ["quads", "conditioning"], "Pool", "cardio", "distance"),
  e("swm-pull-buoy", "Swimming — Pull Buoy Set", "cardio", ["back", "conditioning"], "Pool", "cardio", "distance"),
  e("swm-sprint-50", "Swimming — 50m Sprints", "cardio", ["conditioning"], "Pool", "cardio", "reps"),
  e("swm-flip-turns", "Swimming — Flip Turn Reps", "athletic", ["core"], "Pool", "cardio", "reps"),
  e("swm-dryland-cords", "Swimming — Dryland Stretch Cords", "resistance", ["back", "shoulders"], "Band", "pull", "reps"),
  e("wp-eggbeater", "Water Polo — Eggbeater Treading", "cardio", ["quads", "conditioning"], "Pool", "cardio", "time"),

  // ---------- Combat sports ----------
  e("cmb-shadow-boxing", "Boxing — Shadow Boxing Rounds", "cardio", ["conditioning", "shoulders"], "None", "cardio", "time"),
  e("cmb-heavy-bag", "Boxing — Heavy Bag Rounds", "cardio", ["conditioning", "shoulders"], "Heavy Bag", "cardio", "time"),
  e("cmb-mitt-work", "Boxing — Focus Mitt Rounds", "cardio", ["conditioning"], "Mitts", "cardio", "time"),
  e("cmb-jump-rope-rounds", "Boxing — Jump Rope Rounds", "cardio", ["calves", "conditioning"], "Rope", "cardio", "time"),
  e("cmb-wrestling-sprawl", "Wrestling — Sprawl Drill", "athletic", ["full body", "conditioning"], "Mat", "cardio", "reps"),
  e("cmb-shot-penetration", "Wrestling — Penetration Step Shots", "athletic", ["quads", "conditioning"], "Mat", "cardio", "reps"),
  e("cmb-neck-bridge", "Wrestling — Neck Bridge", "athletic", ["back", "core"], "Mat", "core", "time"),
  e("cmb-stand-ups", "Wrestling — Stand-Up Escapes", "athletic", ["conditioning"], "Mat", "cardio", "reps"),
  e("cmb-bjj-shrimp", "BJJ — Hip Escape (Shrimp)", "athletic", ["core", "conditioning"], "Mat", "core", "reps"),
  e("cmb-bjj-technical-standup", "BJJ — Technical Stand-Up", "athletic", ["core"], "Mat", "core", "reps"),
  e("cmb-mma-clinch-pummel", "MMA — Clinch Pummeling", "athletic", ["back", "conditioning"], "Mat", "cardio", "time"),
  e("cmb-kick-reps", "Muay Thai — Roundhouse Kick Reps", "athletic", ["core", "quads"], "Heavy Bag", "cardio", "reps"),

  // ---------- Hockey / lacrosse ----------
  e("hky-slideboard", "Hockey — Slideboard Intervals", "cardio", ["glutes", "conditioning"], "Slideboard", "cardio", "time"),
  e("hky-stickhandling", "Hockey — Stickhandling Reps", "athletic", ["conditioning"], "Stick", "cardio", "time"),
  e("hky-shooting", "Hockey — Shooting Reps", "athletic", ["core", "shoulders"], "Stick", "cardio", "reps"),
  e("hky-crossover-skate", "Hockey — Crossover Skating Drill", "athletic", ["quads", "glutes"], "Ice", "cardio", "reps"),
  e("lax-wall-ball", "Lacrosse — Wall Ball", "athletic", ["shoulders", "conditioning"], "Lacrosse Stick", "cardio", "time"),
  e("lax-dodging", "Lacrosse — Dodging Cone Drill", "athletic", ["conditioning"], "Cones", "cardio", "reps"),
  e("lax-faceoff", "Lacrosse — Faceoff Reps", "athletic", ["full body"], "Lacrosse Stick", "cardio", "reps"),
  e("fld-hockey-drag-flick", "Field Hockey — Drag Flick Reps", "athletic", ["core"], "Stick", "cardio", "reps"),

  // ---------- Golf / rotational ----------
  e("glf-driver-range", "Golf — Driver Range Reps", "athletic", ["core"], "Golf Club", "cardio", "reps"),
  e("glf-iron-range", "Golf — Iron Range Reps", "athletic", ["core"], "Golf Club", "cardio", "reps"),
  e("glf-putting", "Golf — Putting Ladder", "athletic", ["core"], "Putter", "cardio", "reps"),
  e("glf-rotational-band", "Golf — Banded Rotational Swing", "resistance", ["core"], "Band", "core", "reps"),

  // ---------- Dance / cheer / gymnastics ----------
  e("dnc-plie-series", "Dance — Plié Series", "athletic", ["quads", "mobility"], "Barre", "legs", "reps"),
  e("dnc-releve", "Dance — Relevé Calf Series", "athletic", ["calves"], "Barre", "legs", "reps"),
  e("dnc-leap-series", "Dance — Grand Jeté Leaps", "athletic", ["glutes", "quads"], "Studio", "legs", "reps"),
  e("dnc-turn-drill", "Dance — Pirouette Turn Drill", "athletic", ["core"], "Studio", "cardio", "reps"),
  e("dnc-across-floor", "Dance — Across the Floor Combo", "cardio", ["conditioning"], "Studio", "cardio", "time"),
  e("chr-standing-tumble", "Cheer — Standing Tumbling Reps", "athletic", ["full body"], "Mat", "cardio", "reps"),
  e("chr-jump-series", "Cheer — Toe Touch Jump Series", "athletic", ["quads", "core"], "Mat", "legs", "reps"),
  e("chr-stunt-hold", "Cheer — Stunt Overhead Hold", "athletic", ["shoulders", "core"], "None", "core", "time"),
  e("gym-handstand-walk", "Gymnastics — Handstand Walk", "calisthenics", ["shoulders", "core"], "Bodyweight", "push", "distance"),
  e("gym-ring-support", "Gymnastics — Ring Support Hold", "calisthenics", ["shoulders", "core"], "Rings", "push", "time"),
  e("gym-back-handspring", "Gymnastics — Back Handspring Reps", "athletic", ["full body"], "Mat", "cardio", "reps"),
  e("gym-vault-run", "Gymnastics — Vault Run-Through", "athletic", ["conditioning"], "Vault", "cardio", "reps"),

  // ---------- Other sports ----------
  e("wtr-rowing-2k", "Rowing — 2k Erg Test", "cardio", ["back", "conditioning"], "Machine", "cardio", "time"),
  e("skt-ollie-reps", "Skate — Ollie Reps", "athletic", ["calves", "core"], "Skateboard", "cardio", "reps"),
  e("clb-hangboard", "Climbing — Hangboard Repeaters", "calisthenics", ["back", "biceps"], "Hangboard", "pull", "time"),
  e("clb-bouldering", "Climbing — Bouldering Session", "calisthenics", ["back", "full body"], "Wall", "pull", "time"),
  e("sqh-ghosting", "Squash — Court Ghosting", "cardio", ["conditioning"], "Court", "cardio", "time"),
  e("ult-frisbee-cutting", "Ultimate — Cutting Drill", "athletic", ["conditioning"], "Field", "cardio", "reps"),
  e("rgb-scrum-drive", "Rugby — Scrum Machine Drive", "athletic", ["quads", "back"], "Scrum Machine", "cardio", "reps"),
  e("rgb-tackle-bag", "Rugby — Tackle Bag Reps", "athletic", ["full body"], "Tackle Bag", "cardio", "reps"),
  e("rgb-ruck-clearout", "Rugby — Ruck Clear-Out Drill", "athletic", ["full body", "conditioning"], "Field", "cardio", "reps"),
  e("esp-reaction-lights", "Reaction Light Drill", "athletic", ["conditioning"], "Reaction Lights", "cardio", "time"),
  e("gen-battle-ropes", "Battle Ropes", "cardio", ["shoulders", "conditioning"], "Battle Ropes", "cardio", "time"),
  e("gen-sled-drag", "Backward Sled Drag", "cardio", ["quads", "conditioning"], "Sled", "cardio", "distance"),
  e("gen-tire-flip", "Tire Flip", "athletic", ["full body"], "Tire", "legs", "reps"),
  e("gen-sandbag-carry", "Sandbag Bear Hug Carry", "athletic", ["core", "full body"], "Sandbag", "core", "distance"),
  e("gen-yoke-carry", "Yoke Carry", "athletic", ["core", "full body"], "Yoke", "core", "distance"),
  e("gen-stair-runs", "Stadium Stair Runs", "cardio", ["quads", "conditioning"], "Stadium", "cardio", "reps"),
];
