import type { Exercise, ExerciseCategory } from "./types";

const e = (
  id: string,
  name: string,
  category: ExerciseCategory,
  muscles: Exercise["muscles"],
  equipment: string,
  pattern: Exercise["pattern"],
  metric: Exercise["metric"] = "weight_reps",
): Exercise => ({ id, name, category, muscles, equipment, pattern, metric });

/** Third wave of the library — gym-floor variations athletes actually ask for. */
export const MORE_EXERCISES: Exercise[] = [
  // ---- Arms: curls & extensions ----
  e("db-incline-hammer-curl", "Incline Hammer Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-incline-curl", "Incline Dumbbell Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-seated-hammer-curl", "Seated Hammer Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-cross-body-hammer", "Cross-Body Hammer Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-concentration-curl", "Concentration Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-zottman-curl", "Zottman Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("bb-ez-curl", "EZ-Bar Curl", "resistance", ["biceps"], "Barbell", "pull"),
  e("bb-preacher-curl", "Preacher Curl", "resistance", ["biceps"], "Barbell", "pull"),
  e("bb-reverse-curl", "Reverse Barbell Curl", "resistance", ["biceps"], "Barbell", "pull"),
  e("bb-drag-curl", "Barbell Drag Curl", "resistance", ["biceps"], "Barbell", "pull"),
  e("cbl-bayesian-curl", "Cable Bayesian Curl", "resistance", ["biceps"], "Cable", "pull"),
  e("cbl-rope-hammer-curl", "Cable Rope Hammer Curl", "resistance", ["biceps"], "Cable", "pull"),
  e("mch-preacher-curl", "Machine Preacher Curl", "resistance", ["biceps"], "Machine", "pull"),
  e("db-wrist-curl", "Dumbbell Wrist Curl", "resistance", ["biceps"], "Dumbbell", "pull"),
  e("db-skull-crusher", "Dumbbell Skull Crusher", "resistance", ["triceps"], "Dumbbell", "push"),
  e("bb-skull-crusher", "Barbell Skull Crusher", "resistance", ["triceps"], "Barbell", "push"),
  e("db-overhead-ext", "Overhead Dumbbell Extension", "resistance", ["triceps"], "Dumbbell", "push"),
  e("cbl-overhead-rope-ext", "Cable Overhead Rope Extension", "resistance", ["triceps"], "Cable", "push"),
  e("cbl-rope-pushdown", "Rope Triceps Pushdown", "resistance", ["triceps"], "Cable", "push"),
  e("cbl-single-arm-pushdown", "Single-Arm Cable Pushdown", "resistance", ["triceps"], "Cable", "push"),
  e("db-kickback", "Dumbbell Triceps Kickback", "resistance", ["triceps"], "Dumbbell", "push"),
  e("bb-jm-press", "JM Press", "resistance", ["triceps", "chest"], "Barbell", "push"),
  e("bb-close-grip-bench", "Close-Grip Bench Press", "resistance", ["triceps", "chest"], "Barbell", "push"),

  // ---- Chest ----
  e("db-decline-press", "Decline Dumbbell Press", "resistance", ["chest"], "Dumbbell", "push"),
  e("db-fly", "Dumbbell Chest Fly", "resistance", ["chest"], "Dumbbell", "push"),
  e("cbl-high-low-fly", "High-to-Low Cable Fly", "resistance", ["chest"], "Cable", "push"),
  e("cbl-low-high-fly", "Low-to-High Cable Fly", "resistance", ["chest"], "Cable", "push"),
  e("mch-pec-deck", "Pec Deck Machine", "resistance", ["chest"], "Machine", "push"),
  e("mch-incline-press", "Machine Incline Press", "resistance", ["chest", "shoulders"], "Machine", "push"),
  e("bb-floor-press", "Barbell Floor Press", "resistance", ["chest", "triceps"], "Barbell", "push"),
  e("bb-spoto-press", "Spoto Press", "resistance", ["chest"], "Barbell", "push"),
  e("db-svend-press", "Svend Press", "resistance", ["chest"], "Dumbbell", "push"),

  // ---- Back ----
  e("bb-pendlay-row", "Pendlay Row", "resistance", ["back"], "Barbell", "pull"),
  e("bb-meadows-row", "Meadows Row", "resistance", ["back"], "Barbell", "pull"),
  e("bb-t-bar-row", "T-Bar Row", "resistance", ["back"], "Barbell", "pull"),
  e("mch-chest-supported-row", "Chest-Supported Machine Row", "resistance", ["back"], "Machine", "pull"),
  e("cbl-straight-arm-pulldown", "Straight-Arm Pulldown", "resistance", ["back"], "Cable", "pull"),
  e("cbl-single-arm-pulldown", "Single-Arm Lat Pulldown", "resistance", ["back"], "Cable", "pull"),
  e("cbl-neutral-pulldown", "Neutral-Grip Lat Pulldown", "resistance", ["back", "biceps"], "Cable", "pull"),
  e("bb-shrug", "Barbell Shrug", "resistance", ["back", "shoulders"], "Barbell", "pull"),
  e("db-shrug", "Dumbbell Shrug", "resistance", ["back", "shoulders"], "Dumbbell", "pull"),
  e("bb-rack-pull", "Rack Pull", "resistance", ["back", "hamstrings"], "Barbell", "pull"),
  e("bb-good-morning", "Barbell Good Morning", "resistance", ["hamstrings", "back"], "Barbell", "pull"),
  e("mch-back-ext", "45° Back Extension", "resistance", ["glutes", "back"], "Machine", "pull", "reps"),
  e("cal-inverted-row", "Inverted Row", "calisthenics", ["back", "biceps"], "Bodyweight", "pull", "reps"),

  // ---- Shoulders ----
  e("db-arnold-press", "Arnold Press", "resistance", ["shoulders"], "Dumbbell", "push"),
  e("cbl-lateral-raise", "Cable Lateral Raise", "resistance", ["shoulders"], "Cable", "push"),
  e("db-front-raise", "Dumbbell Front Raise", "resistance", ["shoulders"], "Dumbbell", "push"),
  e("bb-upright-row", "Barbell Upright Row", "resistance", ["shoulders", "back"], "Barbell", "pull"),
  e("db-y-raise", "Prone Y-Raise", "resistance", ["shoulders", "back"], "Dumbbell", "pull"),
  e("bb-landmine-press", "Landmine Press", "resistance", ["shoulders", "chest"], "Barbell", "push"),
  e("bb-z-press", "Seated Z-Press", "resistance", ["shoulders", "core"], "Barbell", "push"),
  e("db-cuban-press", "Cuban Press", "resistance", ["shoulders"], "Dumbbell", "push"),

  // ---- Legs & glutes ----
  e("bb-pause-squat", "Paused Back Squat", "resistance", ["quads"], "Barbell", "legs"),
  e("bb-box-squat", "Box Squat", "resistance", ["quads", "glutes"], "Barbell", "legs"),
  e("bb-safety-bar-squat", "Safety Bar Squat", "resistance", ["quads", "glutes"], "Barbell", "legs"),
  e("bb-zercher-squat", "Zercher Squat", "resistance", ["quads", "core"], "Barbell", "legs"),
  e("bb-split-squat", "Barbell Split Squat", "resistance", ["quads", "glutes"], "Barbell", "legs"),
  e("bb-sumo-deadlift", "Sumo Deadlift", "resistance", ["glutes", "hamstrings"], "Barbell", "pull"),
  e("bb-deficit-deadlift", "Deficit Deadlift", "resistance", ["hamstrings", "back"], "Barbell", "pull"),
  e("bb-trap-bar-deadlift", "Trap Bar Deadlift", "resistance", ["quads", "glutes"], "Barbell", "pull"),
  e("db-single-leg-rdl", "Single-Leg Romanian Deadlift", "resistance", ["hamstrings", "glutes"], "Dumbbell", "pull"),
  e("mch-hack-squat", "Hack Squat", "resistance", ["quads"], "Machine", "legs"),
  e("mch-pendulum-squat", "Pendulum Squat", "resistance", ["quads"], "Machine", "legs"),
  e("mch-belt-squat", "Belt Squat", "resistance", ["quads", "glutes"], "Machine", "legs"),
  e("mch-lying-leg-curl", "Lying Leg Curl", "resistance", ["hamstrings"], "Machine", "legs"),
  e("mch-nordic-curl", "Nordic Hamstring Curl", "calisthenics", ["hamstrings"], "Bodyweight", "legs", "reps"),
  e("mch-hip-abduction", "Hip Abduction Machine", "resistance", ["glutes"], "Machine", "legs"),
  e("mch-hip-adduction", "Hip Adduction Machine", "resistance", ["quads"], "Machine", "legs"),
  e("cbl-kickback", "Cable Glute Kickback", "resistance", ["glutes"], "Cable", "legs"),
  e("cbl-pull-through", "Cable Pull-Through", "resistance", ["glutes", "hamstrings"], "Cable", "pull"),
  e("db-seated-calf-raise", "Seated Calf Raise", "resistance", ["calves"], "Machine", "legs"),
  e("db-single-leg-calf", "Single-Leg Calf Raise", "resistance", ["calves"], "Dumbbell", "legs"),
  e("ath-sled-push", "Sled Push", "athletic", ["quads", "conditioning"], "Sled", "legs", "distance"),
  e("ath-sled-drag", "Backward Sled Drag", "athletic", ["quads", "conditioning"], "Sled", "legs", "distance"),
  e("ath-reverse-lunge-hop", "Reverse Lunge to Hop", "athletic", ["quads", "glutes"], "Bodyweight", "legs", "reps"),

  // ---- Core ----
  e("cal-ab-wheel", "Ab Wheel Rollout", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cbl-crunch", "Cable Crunch", "resistance", ["core"], "Cable", "core"),
  e("cal-v-up", "V-Up", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("cal-hollow-hold", "Hollow Body Hold", "calisthenics", ["core"], "Bodyweight", "core", "time"),
  e("cal-side-plank", "Side Plank", "calisthenics", ["core"], "Bodyweight", "core", "time"),
  e("cal-bird-dog", "Bird Dog", "calisthenics", ["core"], "Bodyweight", "core", "reps"),
  e("ath-mb-rotational-throw", "Rotational Med-Ball Throw", "athletic", ["core", "full body"], "Medicine Ball", "core", "reps"),
  e("ath-landmine-rotation", "Landmine Rotation", "athletic", ["core"], "Barbell", "core"),
  e("kb-suitcase-carry", "Suitcase Carry", "resistance", ["core"], "Kettlebell", "core", "time"),

  // ---- Athletic / sport skill ----
  e("ath-depth-jump", "Depth Jump", "athletic", ["quads", "full body"], "Box", "legs", "reps"),
  e("ath-broad-jump", "Standing Broad Jump", "athletic", ["quads", "glutes"], "Bodyweight", "legs", "reps"),
  e("ath-hurdle-hop", "Hurdle Hop", "athletic", ["quads", "calves"], "Hurdles", "legs", "reps"),
  e("ath-single-leg-bound", "Single-Leg Bound", "athletic", ["glutes", "quads"], "Bodyweight", "legs", "reps"),
  e("ath-sprint-fly", "Flying 20m Sprint", "athletic", ["conditioning"], "Track", "cardio", "distance"),
  e("ath-resisted-sprint", "Resisted Band Sprint", "athletic", ["quads", "conditioning"], "Band", "cardio", "distance"),
  e("ath-tempo-run", "Tempo Run 100m", "athletic", ["conditioning"], "Track", "cardio", "distance"),
  e("ath-mirror-drill", "Reactive Mirror Drill", "athletic", ["conditioning"], "Cones", "cardio", "time"),
  e("ath-dance-turn-series", "Pirouette / Turn Series", "athletic", ["core", "calves"], "Bodyweight", "core", "reps"),
  e("ath-dance-leap", "Grand Jeté Leap Drill", "athletic", ["glutes", "quads"], "Bodyweight", "legs", "reps"),
  e("ath-releve-raise", "Relevé Calf Raise", "athletic", ["calves"], "Bodyweight", "legs", "reps"),
  e("ath-turnout-clamshell", "Turnout Clamshell", "athletic", ["glutes"], "Band", "legs", "reps"),
  e("ath-handstand-hold", "Handstand Hold", "calisthenics", ["shoulders", "core"], "Bodyweight", "push", "time"),
  e("ath-bridge-hold", "Back Bridge Hold", "calisthenics", ["core", "shoulders"], "Bodyweight", "mobility", "time"),
  e("ath-jump-rope-doubles", "Jump Rope Double-Unders", "athletic", ["calves", "conditioning"], "Jump Rope", "cardio", "reps"),
  e("ath-skater-jump", "Skater Jump", "athletic", ["glutes", "quads"], "Bodyweight", "legs", "reps"),

  // ---- Cardio & recovery ----
  e("car-erg-row", "Rowing Erg", "cardio", ["conditioning"], "Rower", "cardio", "distance"),
  e("car-ski-erg", "Ski Erg", "cardio", ["conditioning"], "Ski Erg", "cardio", "distance"),
  e("car-assault-bike", "Assault Bike", "cardio", ["conditioning"], "Bike", "cardio", "time"),
  e("car-stair-climber", "Stair Climber", "cardio", ["conditioning"], "Machine", "cardio", "time"),
  e("car-incline-walk", "Incline Treadmill Walk", "cardio", ["conditioning"], "Treadmill", "cardio", "time"),
  e("car-swim-intervals", "Swim Intervals", "cardio", ["conditioning"], "Pool", "cardio", "distance"),
  e("rec-pigeon", "Pigeon Pose", "recovery", ["mobility"], "Bodyweight", "mobility", "time"),
  e("rec-banded-hip-distraction", "Banded Hip Distraction", "recovery", ["mobility"], "Band", "mobility", "time"),
  e("rec-calf-smash", "Calf Smash", "recovery", ["mobility"], "Foam Roller", "mobility", "time"),
  e("rec-nerve-floss", "Sciatic Nerve Floss", "recovery", ["mobility"], "Bodyweight", "mobility", "reps"),
  e("rec-breathing", "Box Breathing Reset", "recovery", ["mobility"], "None", "mobility", "time"),
];
