import type { RoutineExercise } from "./types";
import type { Program } from "./programs";

const x = (
  exerciseId: string,
  name: string,
  sets: number,
  reps: string,
  supersetGroup: number | null = null,
): RoutineExercise => ({ exerciseId, name, sets, reps, supersetGroup });

/** Sport-specific and goal-specific programs merged into PROGRAMS. */
export const EXTRA_PROGRAMS: Program[] = [
  {
    id: "qb-pocket-power",
    name: "Quarterback — Arm Velocity & Pocket Power",
    tagline: "Rotational power, footwork under pressure and shoulder durability for QBs.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Throwing Power",
        exercises: [
          x("ath-qb-footwork-ladder", "QB Quick-Feet Ladder", 3, "3 passes"),
          x("ath-mb-rotational", "Rotational Med Ball Throw", 5, "5 each"),
          x("ath-qb-throw-net", "QB Accuracy Net Throws", 4, "10 throws"),
          x("bb-landmine-rotation", "Landmine Rotation", 3, "8 each"),
          x("band-external-rotation", "Band External Rotation", 3, "15 each"),
        ],
      },
      {
        day: "Day 2",
        focus: "Lower Strength",
        exercises: [
          x("bb-trapbar-dl", "Trap Bar Deadlift", 4, "5"),
          x("db-bulgarian", "Bulgarian Split Squat", 3, "8 each"),
          x("bb-hip-thrust", "Barbell Hip Thrust", 3, "10"),
          x("cbl-pallof", "Pallof Press", 3, "12 each"),
          x("rec-hip-cars", "Hip CARs", 2, "5 each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Pocket Movement",
        exercises: [
          x("ath-qb-dropback", "QB 3/5/7-Step Dropbacks", 6, "3 reps"),
          x("ath-qb-rollout-throw", "QB Rollout Throws", 4, "8 throws"),
          x("ath-cone-5105", "5-10-5 Pro Agility", 4, "1 rep"),
          x("ath-lateral-bound", "Lateral Skater Bound", 3, "6 each"),
          x("cal-copenhagen-x", "Side Plank", 3, "30s each"),
        ],
      },
      {
        day: "Day 4",
        focus: "Upper Durability",
        exercises: [
          x("db-incline", "Incline Dumbbell Press", 4, "8"),
          x("cal-ring-row", "Ring Row", 4, "10"),
          x("rec-yttw", "Y-T-W Raises", 3, "8 each"),
          x("cbl-face-pull", "Cable Face Pull", 4, "15"),
          x("db-wrist-roller", "Wrist Roller", 3, "45s"),
        ],
      },
    ],
  },
  {
    id: "wr-speed-hands",
    name: "Wide Receiver — Separation Speed & Hands",
    tagline: "Top-end speed, sharp route breaks and catch-radius work.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "lime",
    days: [
      {
        day: "Day 1",
        focus: "Max Velocity",
        exercises: [
          x("ath-aframe", "A-Skips", 3, "20 yd"),
          x("ath-track-wicket", "Wicket Runs", 4, "20 yd"),
          x("car-flying-30", "Flying 30s", 4, "1 rep"),
          x("bb-rdl", "Romanian Deadlift", 4, "6"),
          x("cal-nordic", "Nordic Hamstring Curl", 3, "5"),
        ],
      },
      {
        day: "Day 2",
        focus: "Route Running",
        exercises: [
          x("ath-wr-route-tree", "WR Route Tree Reps", 4, "6 routes"),
          x("ath-wr-release-drill", "WR Press Release Drill", 4, "5 each"),
          x("ath-cone-tdrill", "T-Drill", 4, "1 rep"),
          x("ath-lateral-hurdle-hop", "Lateral Hurdle Hop", 3, "8 each"),
          x("cal-side-plank", "Side Plank", 3, "40s"),
        ],
      },
      {
        day: "Day 3",
        focus: "Hands & Acceleration",
        exercises: [
          x("ath-wr-hands-jugs", "Jugs Machine Catches", 5, "10 catches"),
          x("ath-wr-high-point", "High-Point Catch Drill", 4, "6"),
          x("ath-sled-sprint", "Resisted Sled Sprint", 6, "15 yd"),
          x("ath-single-leg-box-jump", "Single-Leg Box Jump", 3, "4 each"),
          x("cal-hanging-leg-raise", "Hanging Leg Raise", 3, "12"),
        ],
      },
      {
        day: "Day 4",
        focus: "Strength Base",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 4, "5"),
          x("db-bench", "Dumbbell Bench Press", 3, "8"),
          x("cal-weighted-pullup", "Weighted Pull-Up", 4, "5"),
          x("mch-calf-raise", "Standing Calf Raise", 4, "12"),
          x("rec-couch-stretch", "Couch Stretch", 2, "60s each"),
        ],
      },
    ],
  },
  {
    id: "cricket-batter-power",
    name: "Cricket Batter — Bat Speed & Running",
    tagline: "Rotational bat speed, quick singles and heat-tolerant repeat efforts.",
    weeks: 6,
    daysPerWeek: 4,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "flare",
    days: [
      {
        day: "Day 1",
        focus: "Bat Speed",
        exercises: [
          x("ath-cricket-shadow-bat", "Cricket Shadow Batting", 4, "10 shots"),
          x("ath-mb-rotational", "Rotational Med Ball Throw", 5, "5 each"),
          x("cbl-woodchop", "Cable Woodchopper", 3, "12 each"),
          x("db-wrist-roller", "Wrist Roller", 3, "45s"),
          x("cbl-pallof", "Pallof Press", 3, "12 each"),
        ],
      },
      {
        day: "Day 2",
        focus: "Batting Footwork",
        exercises: [
          x("ath-cricket-footwork", "Batting Footwork Drill", 4, "8 reps"),
          x("ath-cricket-throwdowns", "Throwdown Batting Reps", 4, "20 balls"),
          x("ath-reaction-ball", "Reaction Ball Drill", 3, "10"),
          x("db-lateral-lunge", "Lateral Lunge", 3, "8 each"),
          x("cal-deadbug", "Dead Bug", 3, "10 each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Running Between Wickets",
        exercises: [
          x("ath-cricket-running-3s", "Running Between Wickets 3s", 6, "1 rep"),
          x("car-shuttle", "300-Yard Shuttle", 2, "1 rep"),
          x("ath-cone-5105", "5-10-5 Pro Agility", 4, "1 rep"),
          x("db-rdl-single", "Single-Leg Romanian Deadlift", 3, "8 each"),
          x("rec-90-90", "90/90 Hip Switch", 2, "60s"),
        ],
      },
      {
        day: "Day 4",
        focus: "Strength & Fielding",
        exercises: [
          x("bb-front-squat", "Barbell Front Squat", 4, "5"),
          x("ath-cricket-fielding", "Ground Fielding & Throw", 4, "10"),
          x("db-row", "One-Arm Dumbbell Row", 3, "10 each"),
          x("band-external-rotation", "Band External Rotation", 3, "15 each"),
          x("rec-thoracic-open", "Thoracic Open-Book", 2, "8 each"),
        ],
      },
    ],
  },
  {
    id: "cricket-fast-bowler",
    name: "Cricket Fast Bowler — Durability & Pace",
    tagline: "Run-up speed, trunk stiffness and back/shoulder resilience over long spells.",
    weeks: 8,
    daysPerWeek: 3,
    level: "Advanced",
    tracks: ["sport", "strength"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Run-Up Power",
        exercises: [
          x("ath-cricket-bowling-run", "Bowling Run-Up Repeats", 6, "1 rep"),
          x("ath-broad-jump", "Standing Broad Jump", 4, "3"),
          x("bb-trapbar-dl", "Trap Bar Deadlift", 4, "4"),
          x("cal-copenhagen-x", "Side Plank", 3, "30s each"),
          x("mch-back-extension", "45° Back Extension", 3, "12"),
        ],
      },
      {
        day: "Day 2",
        focus: "Trunk & Shoulder",
        exercises: [
          x("cbl-anti-rotation-chop", "Half-Kneeling Cable Chop", 3, "10 each"),
          x("kb-turkish-getup", "Turkish Get-Up", 3, "3 each"),
          x("rec-yttw", "Y-T-W Raises", 3, "8 each"),
          x("cal-ab-wheel", "Ab Wheel Rollout", 3, "8"),
          x("band-pull-apart", "Band Pull-Apart", 3, "20"),
        ],
      },
      {
        day: "Day 3",
        focus: "Legs & Aerobic Base",
        exercises: [
          x("db-bulgarian", "Bulgarian Split Squat", 4, "8 each"),
          x("mch-glute-ham-raise", "Glute-Ham Raise", 3, "8"),
          x("car-zone2-run", "Zone 2 Run", 1, "30 min"),
          x("rec-tibialis-raise", "Tibialis Raise", 3, "15"),
          x("rec-pigeon", "Pigeon Pose", 2, "60s each"),
        ],
      },
    ],
  },
  {
    id: "calisthenics-hypertrophy",
    name: "Calisthenics Hypertrophy",
    tagline: "Build visible size with rings, weighted bodyweight and high-tension holds.",
    weeks: 10,
    daysPerWeek: 4,
    level: "Intermediate",
    tracks: ["hypertrophy", "movement"],
    accent: "lime",
    days: [
      {
        day: "Day 1",
        focus: "Push Volume",
        exercises: [
          x("cal-weighted-dip", "Weighted Dip", 4, "6-8"),
          x("cal-ring-pushup", "Ring Push-Up", 4, "12"),
          x("cal-pseudo-planche-pushup", "Pseudo Planche Push-Up", 3, "10"),
          x("cal-pike-pushup", "Pike Push-Up", 3, "10"),
          x("cal-bench-dip", "Bench Dip", 3, "15"),
        ],
      },
      {
        day: "Day 2",
        focus: "Pull Volume",
        exercises: [
          x("cal-weighted-pullup", "Weighted Pull-Up", 4, "6"),
          x("cal-ring-row", "Ring Row", 4, "12"),
          x("cal-typewriter-pullup", "Typewriter Pull-Up", 3, "5 each"),
          x("cal-scapular-pullup", "Scapular Pull-Up", 3, "10"),
          x("cal-dead-hang", "Dead Hang", 3, "45s"),
        ],
      },
      {
        day: "Day 3",
        focus: "Legs & Core",
        exercises: [
          x("cal-shrimp-squat", "Shrimp Squat", 4, "6 each"),
          x("cal-pistol-squat", "Pistol Squat", 3, "6 each"),
          x("cal-nordic", "Nordic Hamstring Curl", 3, "5"),
          x("cal-single-leg-calf", "Single-Leg Calf Raise", 4, "15 each"),
          x("cal-dragon-flag", "Dragon Flag", 3, "6"),
        ],
      },
      {
        day: "Day 4",
        focus: "Skill & Straight-Arm",
        exercises: [
          x("cal-tuck-planche", "Tuck Planche", 5, "15s"),
          x("cal-front-lever", "Front Lever Hold", 5, "10s"),
          x("cal-handstand-hold", "Wall Handstand Hold", 4, "45s"),
          x("cal-ring-support", "Ring Support Hold", 4, "30s"),
          x("cal-l-sit", "L-Sit Hold", 4, "20s"),
        ],
      },
    ],
  },
  {
    id: "ppl-hypertrophy",
    name: "Push / Pull / Legs Hypertrophy",
    tagline: "Classic 6-day bodybuilding split for maximum muscle growth.",
    weeks: 12,
    daysPerWeek: 6,
    level: "Intermediate",
    tracks: ["hypertrophy", "strength"],
    accent: "flare",
    days: [
      {
        day: "Day 1",
        focus: "Push (Heavy)",
        exercises: [
          x("bb-bench", "Barbell Bench Press", 4, "6"),
          x("db-shoulder-press", "Dumbbell Shoulder Press", 4, "8"),
          x("bb-close-grip-bench", "Close-Grip Bench Press", 3, "8"),
          x("cbl-lateral-raise", "Cable Lateral Raise", 4, "15"),
          x("cbl-triceps-pushdown", "Triceps Pushdown", 3, "12"),
        ],
      },
      {
        day: "Day 2",
        focus: "Pull (Heavy)",
        exercises: [
          x("bb-pendlay-row", "Pendlay Row", 4, "6"),
          x("cal-weighted-pullup", "Weighted Pull-Up", 4, "6"),
          x("cbl-seated-row", "Seated Cable Row", 3, "10"),
          x("db-incline-curl", "Incline Dumbbell Curl", 3, "12"),
          x("bb-shrug", "Barbell Shrug", 3, "15"),
        ],
      },
      {
        day: "Day 3",
        focus: "Legs (Heavy)",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 5, "5"),
          x("bb-rdl", "Romanian Deadlift", 4, "8"),
          x("mch-leg-press", "Leg Press", 3, "12"),
          x("mch-lying-leg-curl", "Lying Leg Curl", 3, "12"),
          x("mch-seated-calf", "Seated Calf Raise", 4, "15"),
        ],
      },
      {
        day: "Day 4",
        focus: "Push (Volume)",
        exercises: [
          x("db-incline", "Incline Dumbbell Press", 4, "10"),
          x("mch-chest-press", "Machine Chest Press", 3, "12"),
          x("db-arnold-press", "Arnold Press", 3, "12"),
          x("mch-pec-deck", "Pec Deck", 3, "15"),
          x("db-overhead-extension", "Overhead Triceps Extension", 3, "12"),
        ],
      },
      {
        day: "Day 5",
        focus: "Pull (Volume)",
        exercises: [
          x("cbl-lat-pulldown", "Lat Pulldown", 4, "12"),
          x("bb-meadows-row", "Meadows Row", 3, "10 each"),
          x("cbl-straight-arm-pulldown", "Straight-Arm Pulldown", 3, "15"),
          x("cbl-rear-delt-fly", "Cable Rear Delt Fly", 4, "15"),
          x("cbl-curl", "Cable Biceps Curl", 4, "12"),
        ],
      },
      {
        day: "Day 6",
        focus: "Legs (Volume)",
        exercises: [
          x("mch-hack-squat", "Hack Squat", 4, "10"),
          x("db-walking-lunge", "Walking Lunge", 3, "12 each"),
          x("mch-leg-ext", "Leg Extension", 4, "15"),
          x("cbl-pull-through", "Cable Pull-Through", 3, "15"),
          x("mch-calf-raise", "Standing Calf Raise", 5, "12"),
        ],
      },
    ],
  },
  {
    id: "powerlifting-total",
    name: "Powerlifting Total Builder",
    tagline: "Squat, bench and deadlift peaking with targeted accessories.",
    weeks: 10,
    daysPerWeek: 4,
    level: "Advanced",
    tracks: ["strength"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Squat Focus",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 5, "3"),
          x("bb-pause-squat", "Pause Back Squat", 3, "3"),
          x("mch-belt-squat", "Belt Squat", 3, "10"),
          x("mch-back-extension", "45° Back Extension", 3, "12"),
          x("cbl-rope-crunch", "Cable Rope Crunch", 3, "15"),
        ],
      },
      {
        day: "Day 2",
        focus: "Bench Focus",
        exercises: [
          x("bb-bench", "Barbell Bench Press", 5, "3"),
          x("bb-spoto-press", "Spoto Press", 3, "5"),
          x("db-incline", "Incline Dumbbell Press", 3, "8"),
          x("bb-jm-press", "JM Press", 3, "8"),
          x("cbl-face-pull", "Cable Face Pull", 4, "15"),
        ],
      },
      {
        day: "Day 3",
        focus: "Deadlift Focus",
        exercises: [
          x("bb-deadlift", "Barbell Deadlift", 5, "2"),
          x("bb-deficit-deadlift", "Deficit Deadlift", 3, "4"),
          x("bb-good-morning", "Good Morning", 3, "8"),
          x("bb-pendlay-row", "Pendlay Row", 3, "8"),
          x("cal-dead-hang", "Dead Hang", 3, "45s"),
        ],
      },
      {
        day: "Day 4",
        focus: "Volume / Accessory",
        exercises: [
          x("bb-front-squat", "Barbell Front Squat", 4, "6"),
          x("bb-close-grip-bench", "Close-Grip Bench Press", 4, "6"),
          x("mch-lying-leg-curl", "Lying Leg Curl", 3, "12"),
          x("bb-ez-curl", "EZ-Bar Curl", 3, "12"),
          x("mch-triceps-dip", "Machine Triceps Dip", 3, "12"),
        ],
      },
    ],
  },
  {
    id: "basketball-guard",
    name: "Basketball Guard — First Step & Motor",
    tagline: "Deceleration strength, lateral quickness and fourth-quarter conditioning.",
    weeks: 6,
    daysPerWeek: 4,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "lime",
    days: [
      {
        day: "Day 1",
        focus: "First Step",
        exercises: [
          x("ath-sled-sprint", "Resisted Sled Sprint", 6, "10 yd"),
          x("bb-trapbar-jump", "Trap Bar Jump", 4, "3"),
          x("db-reverse-lunge", "Reverse Lunge", 3, "8 each"),
          x("ath-basketball-defslide", "Defensive Slide Drill", 4, "30s"),
          x("cal-copenhagen-x", "Side Plank", 3, "30s each"),
        ],
      },
      {
        day: "Day 2",
        focus: "Skill + Handles",
        exercises: [
          x("ath-basketball-handles", "Two-Ball Handling Series", 4, "60s"),
          x("ath-basketball-shooting", "Spot Shooting Reps", 5, "25 shots"),
          x("ath-reaction-ball", "Reaction Ball Drill", 3, "10"),
          x("ath-ladder-lateral", "Agility Ladder — Lateral Runs", 3, "2 passes"),
          x("rec-ankle-dorsi", "Ankle Dorsiflexion Drill", 2, "10 each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Strength",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 4, "5"),
          x("db-bench", "Dumbbell Bench Press", 3, "8"),
          x("cal-pullup", "Pull-Up", 4, "AMRAP"),
          x("mch-glute-ham-raise", "Glute-Ham Raise", 3, "8"),
          x("cal-hanging-leg-raise", "Hanging Leg Raise", 3, "12"),
        ],
      },
      {
        day: "Day 4",
        focus: "Conditioning",
        exercises: [
          x("car-suicides", "Court Suicides", 6, "1 rep"),
          x("car-beep-test", "Yo-Yo / Beep Test", 1, "1 test"),
          x("ath-lateral-bound", "Lateral Skater Bound", 3, "8 each"),
          x("car-jump-rope", "Jump Rope", 4, "60s"),
          x("rec-walk", "Recovery Walk", 1, "10 min"),
        ],
      },
    ],
  },
  {
    id: "sprinter-track",
    name: "Track Sprinter — 100/200m Build",
    tagline: "Block starts, max velocity mechanics and speed-endurance.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Advanced",
    tracks: ["speed", "sport"],
    accent: "flare",
    days: [
      {
        day: "Day 1",
        focus: "Acceleration",
        exercises: [
          x("ath-track-block-start", "Sprint Block Starts", 6, "20m"),
          x("ath-band-resisted-sprint", "Band-Resisted Sprint", 4, "15m"),
          x("bb-back-squat", "Barbell Back Squat", 4, "3"),
          x("ath-bounds", "Alternating Bounds", 4, "6 each"),
          x("cal-hollow-hold", "Hollow Body Hold", 3, "30s"),
        ],
      },
      {
        day: "Day 2",
        focus: "Max Velocity",
        exercises: [
          x("ath-track-wicket", "Wicket Runs", 5, "30m"),
          x("car-flying-30", "Flying 30s", 4, "1 rep"),
          x("cal-nordic", "Nordic Hamstring Curl", 4, "5"),
          x("ath-pogo", "Pogo Hops", 4, "15"),
          x("rec-hamstring-floss", "Hamstring Nerve Floss", 2, "10 each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Speed Endurance",
        exercises: [
          x("car-sprint-100", "100m Sprint", 5, "1 rep"),
          x("car-400-repeats", "400m Repeats", 3, "1 rep"),
          x("bb-hip-thrust", "Barbell Hip Thrust", 3, "8"),
          x("mch-calf-raise", "Standing Calf Raise", 4, "12"),
          x("rec-couch-stretch", "Couch Stretch", 2, "60s each"),
        ],
      },
      {
        day: "Day 4",
        focus: "Power Lifting Day",
        exercises: [
          x("oly-hang-clean", "Hang Power Clean", 5, "3"),
          x("ath-depth-jump", "Depth Jump", 4, "3"),
          x("bb-rdl", "Romanian Deadlift", 4, "6"),
          x("cbl-pallof", "Pallof Press", 3, "12 each"),
          x("rec-90-90", "90/90 Hip Switch", 2, "60s"),
        ],
      },
    ],
  },
  {
    id: "swimmer-dryland",
    name: "Swimmer Dryland Power",
    tagline: "Pull strength, shoulder health and explosive block starts.",
    weeks: 6,
    daysPerWeek: 3,
    level: "Intermediate",
    tracks: ["sport", "endurance"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Pull Power",
        exercises: [
          x("cal-pullup", "Pull-Up", 4, "8"),
          x("cbl-straight-arm-pulldown", "Straight-Arm Pulldown", 4, "15"),
          x("car-ski-erg", "Ski Erg Intervals", 6, "30s"),
          x("db-pullover", "Dumbbell Pullover", 3, "12"),
          x("band-external-rotation", "Band External Rotation", 3, "15 each"),
        ],
      },
      {
        day: "Day 2",
        focus: "Starts & Turns",
        exercises: [
          x("ath-swim-starts", "Block Starts", 6, "1 rep"),
          x("ath-box-jump", "Box Jump", 4, "4"),
          x("bb-front-squat", "Barbell Front Squat", 4, "5"),
          x("cal-hollow-hold", "Hollow Body Hold", 4, "30s"),
          x("rec-shoulder-cars", "Shoulder CARs", 2, "5 each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Aerobic + Core",
        exercises: [
          x("car-swim-intervals", "Swim Intervals", 10, "100m"),
          x("car-swim-kick", "Kickboard Set", 4, "50m"),
          x("cal-ab-wheel", "Ab Wheel Rollout", 3, "10"),
          x("cal-superman", "Superman Hold", 3, "30s"),
          x("rec-easy-swim", "Easy Recovery Swim", 1, "8 min"),
        ],
      },
    ],
  },
  {
    id: "wrestling-strength",
    name: "Wrestling — Grip, Scramble & Gas Tank",
    tagline: "Positional strength, neck resilience and relentless conditioning.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Advanced",
    tracks: ["sport", "strength"],
    accent: "flare",
    days: [
      {
        day: "Day 1",
        focus: "Full-Body Strength",
        exercises: [
          x("bb-trapbar-dl", "Trap Bar Deadlift", 5, "4"),
          x("cal-weighted-pullup", "Weighted Pull-Up", 4, "5"),
          x("bb-front-squat", "Barbell Front Squat", 4, "5"),
          x("mch-neck-flexion", "Neck Flexion / Extension", 3, "15"),
          x("db-farmer", "Farmer's Carry", 4, "45s"),
        ],
      },
      {
        day: "Day 2",
        focus: "Shots & Scramble",
        exercises: [
          x("ath-wrestling-shots", "Penetration Step Shots", 6, "10"),
          x("str-sandbag-clean", "Sandbag Clean over Shoulder", 5, "5"),
          x("cal-bear-crawl", "Bear Crawl", 4, "20 yd"),
          x("ath-wrestling-bridge", "Neck Bridge Hold", 3, "30s"),
          x("kb-swing", "Kettlebell Swing", 4, "15"),
        ],
      },
      {
        day: "Day 3",
        focus: "Grip & Pull",
        exercises: [
          x("cal-dead-hang", "Dead Hang", 4, "45s"),
          x("db-renegade-row", "Renegade Row", 3, "8 each"),
          x("str-tire-flip", "Tire Flip", 4, "6"),
          x("db-wrist-roller", "Wrist Roller", 3, "45s"),
          x("cal-l-sit", "L-Sit Hold", 3, "20s"),
        ],
      },
      {
        day: "Day 4",
        focus: "Conditioning",
        exercises: [
          x("car-assault-bike", "Air Bike Intervals", 8, "30s"),
          x("car-battle-ropes", "Battle Ropes", 5, "30s"),
          x("car-tabata", "Tabata Circuit", 1, "8 min"),
          x("cal-burpee", "Burpee", 4, "15"),
          x("rec-box-breathing", "Box Breathing Reset", 1, "5 min"),
        ],
      },
    ],
  },
  {
    id: "volleyball-vertical",
    name: "Volleyball — Approach Jump & Shoulder",
    tagline: "Repeat jump capacity, blocking footwork and hitting-shoulder care.",
    weeks: 6,
    daysPerWeek: 3,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "lime",
    days: [
      {
        day: "Day 1",
        focus: "Jump Power",
        exercises: [
          x("ath-volleyball-approach", "Spike Approach Jumps", 6, "3"),
          x("ath-depth-jump", "Depth Jump", 4, "3"),
          x("bb-back-squat", "Barbell Back Squat", 4, "4"),
          x("mch-calf-raise", "Standing Calf Raise", 4, "12"),
          x("cal-hollow-hold", "Hollow Body Hold", 3, "30s"),
        ],
      },
      {
        day: "Day 2",
        focus: "Court Movement",
        exercises: [
          x("ath-volleyball-blocking", "Blocking Footwork", 4, "8"),
          x("ath-lateral-hurdle-hop", "Lateral Hurdle Hop", 4, "8 each"),
          x("ath-ladder-inout", "Agility Ladder — In & Outs", 3, "2 passes"),
          x("db-lateral-lunge", "Lateral Lunge", 3, "8 each"),
          x("rec-ankle-dorsi", "Ankle Dorsiflexion Drill", 2, "10 each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Shoulder & Posterior",
        exercises: [
          x("rec-yttw", "Y-T-W Raises", 3, "8 each"),
          x("cbl-face-pull", "Cable Face Pull", 4, "15"),
          x("bb-rdl", "Romanian Deadlift", 4, "6"),
          x("cal-nordic", "Nordic Hamstring Curl", 3, "5"),
          x("rec-thoracic-open", "Thoracic Open-Book", 2, "8 each"),
        ],
      },
    ],
  },
  {
    id: "distance-runner-strength",
    name: "Distance Runner Strength Support",
    tagline: "Injury-proofing and running economy for 5K–half marathon athletes.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Beginner",
    tracks: ["endurance", "strength"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Easy Aerobic",
        exercises: [
          x("car-zone2-run", "Zone 2 Run", 1, "45 min"),
          x("rec-tibialis-raise", "Tibialis Raise", 3, "15"),
          x("cal-single-leg-calf", "Single-Leg Calf Raise", 3, "20 each"),
          x("cal-bird-dog", "Bird Dog", 3, "10 each"),
          x("rec-calf-stretch", "Wall Calf Stretch", 2, "45s each"),
        ],
      },
      {
        day: "Day 2",
        focus: "Threshold",
        exercises: [
          x("car-tempo-run", "Tempo Run", 1, "25 min"),
          x("car-800-repeats", "800m Repeats", 4, "1 rep"),
          x("cal-glute-bridge", "Glute Bridge", 3, "15"),
          x("cal-side-plank", "Side Plank", 3, "40s"),
          x("rec-pigeon", "Pigeon Pose", 2, "60s each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Strength",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 3, "6"),
          x("db-step-up", "Dumbbell Step-Up", 3, "10 each"),
          x("cal-nordic", "Nordic Hamstring Curl", 3, "4"),
          x("band-lateral-walk", "Banded Lateral Walk", 3, "15 each"),
          x("cal-deadbug", "Dead Bug", 3, "10 each"),
        ],
      },
      {
        day: "Day 4",
        focus: "Hills & Long",
        exercises: [
          x("car-hill-sprint", "Hill Sprints", 8, "1 rep"),
          x("car-long-run", "Long Slow Distance Run", 1, "10 mi"),
          x("rec-foam-quads", "Foam Roll — Quads", 1, "3 min"),
          x("rec-hamstring-floss", "Hamstring Nerve Floss", 2, "10 each"),
          x("rec-nsdr", "NSDR / Yoga Nidra", 1, "15 min"),
        ],
      },
    ],
  },
  {
    id: "football-lineman-mass",
    name: "Football Lineman — Mass & Drive",
    tagline: "Brutal lower-body strength, hand power and 5-second effort conditioning.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Advanced",
    tracks: ["sport", "strength"],
    accent: "flare",
    days: [
      {
        day: "Day 1",
        focus: "Max Lower",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 5, "3"),
          x("bb-safety-bar-squat", "Safety Bar Squat", 3, "6"),
          x("mch-belt-squat", "Belt Squat", 3, "10"),
          x("mch-neck-harness", "Neck Harness Extension", 3, "12"),
          x("db-farmer", "Farmer's Carry", 3, "40s"),
        ],
      },
      {
        day: "Day 2",
        focus: "Max Upper",
        exercises: [
          x("bb-bench", "Barbell Bench Press", 5, "3"),
          x("str-log-press", "Log Overhead Press", 4, "5"),
          x("bb-pendlay-row", "Pendlay Row", 4, "6"),
          x("bb-close-grip-bench", "Close-Grip Bench Press", 3, "8"),
          x("cbl-face-pull", "Cable Face Pull", 3, "15"),
        ],
      },
      {
        day: "Day 3",
        focus: "Drive & Hands",
        exercises: [
          x("ath-lineman-sled", "Blocking Sled Drive", 6, "10 yd"),
          x("ath-mb-chest-pass", "Explosive Chest Pass", 5, "5"),
          x("str-sandbag-carry", "Sandbag Bear Hug Carry", 4, "30 yd"),
          x("ath-cone-5105", "5-10-5 Pro Agility", 3, "1 rep"),
          x("cbl-pallof", "Pallof Press", 3, "12 each"),
        ],
      },
      {
        day: "Day 4",
        focus: "Posterior & Conditioning",
        exercises: [
          x("bb-trapbar-dl", "Trap Bar Deadlift", 4, "5"),
          x("mch-reverse-hyper", "Reverse Hyperextension", 3, "12"),
          x("str-sled-drag", "Backward Sled Drag", 5, "20 yd"),
          x("car-assault-bike", "Air Bike Intervals", 8, "15s"),
          x("rec-90-90", "90/90 Hip Switch", 2, "60s"),
        ],
      },
    ],
  },
  {
    id: "baseball-pitcher-velo",
    name: "Baseball Pitcher — Velo & Arm Care",
    tagline: "Lower-half drive, arm-path power and daily shoulder maintenance.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Lower Half Drive",
        exercises: [
          x("bb-rdl", "Romanian Deadlift", 4, "6"),
          x("db-bulgarian", "Bulgarian Split Squat", 3, "8 each"),
          x("ath-lateral-bound", "Lateral Skater Bound", 4, "6 each"),
          x("cbl-pull-through", "Cable Pull-Through", 3, "12"),
          x("cal-copenhagen-x", "Side Plank", 3, "30s each"),
        ],
      },
      {
        day: "Day 2",
        focus: "Arm Path Power",
        exercises: [
          x("ath-mb-rotational", "Rotational Med Ball Throw", 6, "4 each"),
          x("ath-mb-shotput", "Med Ball Shot-Put Throw", 4, "5 each"),
          x("bb-landmine-rotation", "Landmine Rotation", 3, "8 each"),
          x("kb-windmill", "Kettlebell Windmill", 3, "6 each"),
          x("rec-scap-pushup", "Scapular Push-Up", 3, "12"),
        ],
      },
      {
        day: "Day 3",
        focus: "Pull & Upper",
        exercises: [
          x("cal-chinup", "Chin-Up", 4, "6"),
          x("db-row", "One-Arm Dumbbell Row", 4, "10 each"),
          x("rec-yttw", "Y-T-W Raises", 3, "8 each"),
          x("band-external-rotation", "Band External Rotation", 4, "15 each"),
          x("db-wrist-roller", "Wrist Roller", 3, "45s"),
        ],
      },
      {
        day: "Day 4",
        focus: "Recovery Day",
        exercises: [
          x("car-zone2-run", "Zone 2 Run", 1, "20 min"),
          x("rec-thoracic-extension", "Foam Roller Thoracic Extension", 2, "10"),
          x("rec-shoulder-cars", "Shoulder CARs", 2, "5 each"),
          x("rec-childs-pose", "Child's Pose", 2, "60s"),
          x("rec-nsdr", "NSDR / Yoga Nidra", 1, "15 min"),
        ],
      },
    ],
  },
  {
    id: "tennis-court-speed",
    name: "Tennis — Court Speed & Serve Power",
    tagline: "Multi-directional footwork, serve velocity and match-length endurance.",
    weeks: 6,
    daysPerWeek: 3,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "lime",
    days: [
      {
        day: "Day 1",
        focus: "Footwork",
        exercises: [
          x("ath-tennis-split-step", "Split-Step Reaction Drill", 5, "8"),
          x("ath-ladder-lateral", "Agility Ladder — Lateral Runs", 3, "2 passes"),
          x("ath-cone-tdrill", "T-Drill", 4, "1 rep"),
          x("db-lateral-lunge", "Lateral Lunge", 3, "8 each"),
          x("cal-side-plank", "Side Plank", 3, "40s"),
        ],
      },
      {
        day: "Day 2",
        focus: "Serve Power",
        exercises: [
          x("ath-tennis-serve", "Serve Basket Reps", 5, "10 serves"),
          x("ath-mb-overhead", "Overhead Med Ball Throw", 4, "5"),
          x("db-shoulder-press", "Dumbbell Shoulder Press", 3, "8"),
          x("cbl-woodchop", "Cable Woodchopper", 3, "12 each"),
          x("band-external-rotation", "Band External Rotation", 3, "15 each"),
        ],
      },
      {
        day: "Day 3",
        focus: "Strength & Endurance",
        exercises: [
          x("bb-front-squat", "Barbell Front Squat", 4, "5"),
          x("db-rdl-single", "Single-Leg Romanian Deadlift", 3, "8 each"),
          x("car-shuttle", "300-Yard Shuttle", 3, "1 rep"),
          x("car-jump-rope", "Jump Rope", 4, "60s"),
          x("rec-pigeon", "Pigeon Pose", 2, "60s each"),
        ],
      },
    ],
  },
  {
    id: "hockey-power-skating",
    name: "Hockey — Stride Power & Edge Work",
    tagline: "Lateral hip strength, crossover power and shift-length conditioning.",
    weeks: 6,
    daysPerWeek: 3,
    level: "Intermediate",
    tracks: ["sport", "speed"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Stride Power",
        exercises: [
          x("ath-hockey-crossovers", "Crossover Skating Drill", 5, "2 laps"),
          x("ath-lateral-bound", "Lateral Skater Bound", 5, "6 each"),
          x("bb-back-squat", "Barbell Back Squat", 4, "5"),
          x("mch-hip-abduction", "Hip Abduction Machine", 3, "15"),
          x("cal-copenhagen-x", "Side Plank", 3, "30s each"),
        ],
      },
      {
        day: "Day 2",
        focus: "Posterior & Core",
        exercises: [
          x("bb-trapbar-dl", "Trap Bar Deadlift", 4, "5"),
          x("mch-glute-ham-raise", "Glute-Ham Raise", 3, "8"),
          x("cbl-anti-rotation-chop", "Half-Kneeling Cable Chop", 3, "10 each"),
          x("cal-ab-wheel", "Ab Wheel Rollout", 3, "10"),
          x("rec-frog", "Frog Stretch", 2, "60s"),
        ],
      },
      {
        day: "Day 3",
        focus: "Shift Conditioning",
        exercises: [
          x("car-assault-bike", "Air Bike Intervals", 8, "40s"),
          x("car-row-erg", "Rowing Erg", 5, "250m"),
          x("cal-jump-squat", "Bodyweight Jump Squat", 4, "12"),
          x("car-jump-rope", "Jump Rope", 3, "90s"),
          x("rec-bike-flush", "Recovery Spin", 1, "8 min"),
        ],
      },
    ],
  },
  {
    id: "gym-starter-full-body",
    name: "Gym Starter — Full Body 3x/Week",
    tagline: "Your first 6 weeks in the weight room: simple lifts, real progress.",
    weeks: 6,
    daysPerWeek: 3,
    level: "Beginner",
    tracks: ["strength", "movement"],
    accent: "lime",
    days: [
      {
        day: "Day A",
        focus: "Squat Emphasis",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 3, "8"),
          x("db-bench", "Dumbbell Bench Press", 3, "10"),
          x("cbl-seated-row", "Seated Cable Row", 3, "12"),
          x("cal-plank", "Front Plank", 3, "30s"),
          x("mch-calf-raise", "Standing Calf Raise", 3, "15"),
        ],
      },
      {
        day: "Day B",
        focus: "Hinge Emphasis",
        exercises: [
          x("bb-trapbar-dl", "Trap Bar Deadlift", 3, "6"),
          x("db-shoulder-press", "Dumbbell Shoulder Press", 3, "10"),
          x("cbl-lat-pulldown", "Lat Pulldown", 3, "12"),
          x("cal-glute-bridge", "Glute Bridge", 3, "15"),
          x("cal-deadbug", "Dead Bug", 3, "10 each"),
        ],
      },
      {
        day: "Day C",
        focus: "Machines & Carries",
        exercises: [
          x("mch-leg-press", "Leg Press", 3, "12"),
          x("mch-chest-press", "Machine Chest Press", 3, "12"),
          x("mch-assisted-pullup", "Assisted Pull-Up Machine", 3, "8"),
          x("db-farmer", "Farmer's Carry", 3, "40s"),
          x("rec-worlds-greatest", "World's Greatest Stretch", 2, "60s"),
        ],
      },
    ],
  },
  {
    id: "cut-conditioning",
    name: "Lean-Out Conditioning Circuit",
    tagline: "Keep muscle, torch conditioning — 4 weeks of dense circuit work.",
    weeks: 4,
    daysPerWeek: 4,
    level: "Beginner",
    tracks: ["endurance", "movement"],
    accent: "flare",
    days: [
      {
        day: "Day 1",
        focus: "Full Body Circuit",
        exercises: [
          x("db-thruster", "Dumbbell Thruster", 4, "12", 1),
          x("cal-burpee", "Burpee", 4, "10", 1),
          x("kb-swing", "Kettlebell Swing", 4, "15"),
          x("cal-mountain-climber", "Mountain Climber", 4, "40s"),
          x("car-jump-rope", "Jump Rope", 4, "60s"),
        ],
      },
      {
        day: "Day 2",
        focus: "Intervals",
        exercises: [
          x("car-treadmill", "Treadmill Intervals", 1, "20 min"),
          x("car-row-erg", "Rowing Erg", 6, "250m"),
          x("cal-v-up", "V-Up", 3, "15"),
          x("cal-russian-twist", "Russian Twist", 3, "20"),
          x("rec-childs-pose", "Child's Pose", 2, "60s"),
        ],
      },
      {
        day: "Day 3",
        focus: "Strength Circuit",
        exercises: [
          x("db-goblet-curtsy", "Curtsy Lunge", 3, "12 each"),
          x("cal-pushup", "Push-Up", 4, "AMRAP"),
          x("cal-inverted-row", "Inverted Row", 4, "12"),
          x("db-suitcase-carry", "Suitcase Carry", 3, "40s each"),
          x("cal-wall-sit", "Wall Sit", 3, "45s"),
        ],
      },
      {
        day: "Day 4",
        focus: "Long Easy",
        exercises: [
          x("car-rucking", "Weighted Ruck", 1, "3 mi"),
          x("car-cycling", "Steady-State Cycling", 1, "30 min"),
          x("rec-foam-tspine", "Foam Roll — T-Spine", 1, "3 min"),
          x("rec-downdog", "Downward Dog", 2, "45s"),
          x("rec-box-breathing", "Box Breathing Reset", 1, "5 min"),
        ],
      },
    ],
  },
  {
    id: "olympic-weightlifting-base",
    name: "Olympic Weightlifting Base",
    tagline: "Snatch and clean & jerk technique with squat strength.",
    weeks: 8,
    daysPerWeek: 4,
    level: "Advanced",
    tracks: ["strength", "speed"],
    accent: "cyan",
    days: [
      {
        day: "Day 1",
        focus: "Snatch",
        exercises: [
          x("oly-muscle-snatch", "Muscle Snatch", 4, "3"),
          x("oly-power-snatch", "Power Snatch", 5, "2"),
          x("oly-snatch-pull", "Snatch Pull", 4, "3"),
          x("bb-overhead-squat", "Overhead Squat", 4, "3"),
          x("cal-hollow-hold", "Hollow Body Hold", 3, "30s"),
        ],
      },
      {
        day: "Day 2",
        focus: "Clean & Jerk",
        exercises: [
          x("oly-hang-clean", "Hang Power Clean", 5, "2"),
          x("oly-split-jerk", "Split Jerk", 5, "2"),
          x("oly-clean-pull", "Clean Pull", 4, "3"),
          x("bb-front-squat", "Barbell Front Squat", 4, "4"),
          x("mch-back-extension", "45° Back Extension", 3, "12"),
        ],
      },
      {
        day: "Day 3",
        focus: "Squat Strength",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 5, "4"),
          x("bb-pause-squat", "Pause Back Squat", 3, "3"),
          x("bb-seated-ohp", "Seated Barbell Overhead Press", 4, "6"),
          x("bb-pendlay-row", "Pendlay Row", 3, "8"),
          x("rec-deep-squat-hold", "Deep Squat Hold", 3, "60s"),
        ],
      },
      {
        day: "Day 4",
        focus: "Technique & Accessory",
        exercises: [
          x("oly-snatch", "Full Snatch", 6, "1"),
          x("oly-clean-jerk", "Clean & Jerk", 6, "1"),
          x("oly-ohs-complex", "Snatch Balance", 4, "2"),
          x("cbl-rope-crunch", "Cable Rope Crunch", 3, "15"),
          x("rec-shoulder-cars", "Shoulder CARs", 2, "5 each"),
        ],
      },
    ],
  },
  {
    id: "soccer-midfielder-engine",
    name: "Soccer Midfielder — 90-Minute Engine",
    tagline: "Aerobic power, repeat sprints and groin/hamstring protection.",
    weeks: 6,
    daysPerWeek: 4,
    level: "Intermediate",
    tracks: ["sport", "endurance"],
    accent: "lime",
    days: [
      {
        day: "Day 1",
        focus: "Aerobic Power",
        exercises: [
          x("car-400-repeats", "400m Repeats", 6, "1 rep"),
          x("ath-soccer-rondo", "Rondo Possession", 4, "4 min"),
          x("cal-nordic", "Nordic Hamstring Curl", 3, "5"),
          x("cal-copenhagen-x", "Side Plank", 3, "30s each"),
          x("rec-walk", "Recovery Walk", 1, "10 min"),
        ],
      },
      {
        day: "Day 2",
        focus: "Repeat Sprint",
        exercises: [
          x("car-sprint-40", "40-Yard Sprint", 8, "1 rep"),
          x("ath-cone-5105", "5-10-5 Pro Agility", 4, "1 rep"),
          x("ath-soccer-finishing", "Finishing Reps", 4, "8 shots"),
          x("db-reverse-lunge", "Reverse Lunge", 3, "8 each"),
          x("rec-90-90", "90/90 Hip Switch", 2, "60s"),
        ],
      },
      {
        day: "Day 3",
        focus: "Strength",
        exercises: [
          x("bb-back-squat", "Barbell Back Squat", 4, "5"),
          x("bb-hip-thrust", "Barbell Hip Thrust", 3, "10"),
          x("mch-hip-adduction", "Hip Adduction Machine", 3, "15"),
          x("cal-pullup", "Pull-Up", 3, "AMRAP"),
          x("cal-bird-dog", "Bird Dog", 3, "10 each"),
        ],
      },
      {
        day: "Day 4",
        focus: "Recovery + Skill",
        exercises: [
          x("car-zone2-run", "Zone 2 Run", 1, "30 min"),
          x("ath-soccer-rondo", "Rondo Possession", 3, "5 min"),
          x("rec-foam-quads", "Foam Roll — Quads", 1, "3 min"),
          x("rec-cossack", "Cossack Squat", 3, "8 each"),
          x("rec-nsdr", "NSDR / Yoga Nidra", 1, "15 min"),
        ],
      },
    ],
  },
];
